%%

script_path = fileparts(mfilename('fullpath'));
addpath(fullfile(script_path,'BSI'));

N_rho = size(rho,1);
N_theta = size(rho,2);
N_phi = size(rho,3);
Drho = rho(end,1,1)-rho(1,1,1);
I1 = ones(N_rho,N_theta,N_phi);

%% Bspline Setting

order = uint64(5);

isperiodic_3d = [false,true,true]';
if fullTorus == 1
    phi_period = 2*pi;
else
    phi_period = 2*pi/double(NFP);
end
range_3d = {[double(rho(1,1,1)),double(rho(end,1,1))];[double(theta_pest(1,1,1)),double(theta_pest(1,1,1))+2*pi];[double(phi(1,1,1)),double(phi(1,1,1))+phi_period]};

coor_interp_3d = double([rho(:),theta_pest(:),phi(:)]);

interp_3d_ = @(f, drho, dtheta, dphi) reshape(bspline(order,isperiodic_3d,range_3d,double(f),coor_interp_3d,uint64([drho;dtheta;dphi])),N_rho,N_theta,N_phi);

interp_3d_d1_ = @(f) deal(interp_3d_(f,0,0,0),interp_3d_(f,1,0,0),interp_3d_(f,0,1,0),interp_3d_(f,0,0,1));

%% q derivative

dq_dr = -diota_dr./iota.^2;
dq_dr2 = -diota_dr2./iota.^2+2*diota_dr.^2./iota.^3;

%% 3d variable

dB_drho=dB_dr+(-1).*dB_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1);

dB_dtheta=dB_dt.*(I1+dlambda_dt).^(-1);

dB_dphi=dB_dz+(-1).*dB_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz;

dB_drho2=(I1+dlambda_dt).^(-3).*(dB_dt2.*dlambda_dr.^2.*(I1+dlambda_dt)+(I1+ ...
dlambda_dt).^2.*((-2).*dB_drdt.*dlambda_dr+dB_dr2.*(I1+dlambda_dt)) ...
+(-1).*dB_dt.*((I1+dlambda_dt).*((-2).*dlambda_dr.*dlambda_drdt+ ...
dlambda_dr2.*(I1+dlambda_dt))+dlambda_dr.^2.*dlambda_dt2));

dB_dtheta2=(I1+dlambda_dt).^(-3).*(dB_dt2.*(I1+dlambda_dt)+(-1).*dB_dt.* ...
dlambda_dt2);

dB_dphi2=dB_dz2+(I1+dlambda_dt).^(-3).*dlambda_dz.*((-2).*dB_dtdz.*(I1+ ...
dlambda_dt).^2+dB_dt2.*(I1+dlambda_dt).*dlambda_dz+dB_dt.*(2.*(I1+ ...
dlambda_dt).*dlambda_dtdz+(-1).*dlambda_dt2.*dlambda_dz))+(-1).* ...
dB_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz2;

dB_drhodtheta=(I1+dlambda_dt).^(-3).*((-1).*dB_dt2.*dlambda_dr.*(I1+dlambda_dt)+ ...
dB_drdt.*(I1+dlambda_dt).^2+dB_dt.*((-1).*dlambda_drdt.*(I1+ ...
dlambda_dt)+dlambda_dr.*dlambda_dt2));

dB_drhodphi=dB_drdz+(-1).*dB_dtdz.*dlambda_dr.*(I1+dlambda_dt).^(-1)+(-1).* ...
dB_dt.*dlambda_drdz.*(I1+dlambda_dt).^(-1)+dB_dt.*dlambda_dr.*(I1+ ...
dlambda_dt).^(-2).*dlambda_dtdz+(I1+dlambda_dt).^(-3).*(dB_dt2.* ...
dlambda_dr.*(I1+dlambda_dt)+(-1).*dB_drdt.*(I1+dlambda_dt).^2+ ...
dB_dt.*(dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.* ...
dlambda_dt2)).*dlambda_dz;

dB_dthetadphi=(I1+dlambda_dt).^(-3).*(dB_dtdz.*(I1+dlambda_dt).^2+(-1).*dB_dt2.*( ...
I1+dlambda_dt).*dlambda_dz+(-1).*dB_dt.*((I1+dlambda_dt).* ...
dlambda_dtdz+(-1).*dlambda_dt2.*dlambda_dz));


%% PEST Metric

gconPEST=reshape({gcon_rr;
dlambda_dr.*gcon_rr+(I1+dlambda_dt).*gcon_rt+dlambda_dz.*gcon_rz;
gcon_rz;
dlambda_dr.*gcon_rr+(I1+dlambda_dt).*gcon_rt+dlambda_dz.*gcon_rz;
dlambda_dr.^2.*gcon_rr+2.*dlambda_dr.*gcon_rt+2.*dlambda_dr.* ...
dlambda_dt.*gcon_rt+2.*dlambda_dr.*dlambda_dz.*gcon_rz+(I1+ ...
dlambda_dt).^2.*gcon_tt+2.*(I1+dlambda_dt).*dlambda_dz.*gcon_tz+ ...
dlambda_dz.^2.*gcon_zz;
dlambda_dr.*gcon_rz+(I1+dlambda_dt).*gcon_tz+dlambda_dz.*gcon_zz;
gcon_rz;
dlambda_dr.*gcon_rz+(I1+dlambda_dt).*gcon_tz+dlambda_dz.*gcon_zz;
gcon_zz;
},3,3);


dgconPEST_drho=reshape({dgcon_rr_dr+(-1).*dgcon_rr_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1);
dgcon_rr_dr.*dlambda_dr+dgcon_rt_dr.*(I1+dlambda_dt)+dgcon_rz_dr.* ...
dlambda_dz+dlambda_dr2.*gcon_rr+dlambda_drdt.*gcon_rt+ ...
dlambda_drdz.*gcon_rz+(-1).*dlambda_dr.*(I1+dlambda_dt).^(-1).*( ...
dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+dlambda_dt)+dgcon_rz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rr+dlambda_dt2.*gcon_rt+ ...
dlambda_dtdz.*gcon_rz);
dgcon_rz_dr+(-1).*dgcon_rz_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1);
dgcon_rr_dr.*dlambda_dr+dgcon_rt_dr.*(I1+dlambda_dt)+dgcon_rz_dr.* ...
dlambda_dz+dlambda_dr2.*gcon_rr+dlambda_drdt.*gcon_rt+ ...
dlambda_drdz.*gcon_rz+(-1).*dlambda_dr.*(I1+dlambda_dt).^(-1).*( ...
dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+dlambda_dt)+dgcon_rz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rr+dlambda_dt2.*gcon_rt+ ...
dlambda_dtdz.*gcon_rz);
2.*dgcon_rt_dr.*dlambda_dr+dgcon_rr_dr.*dlambda_dr.^2+2.* ...
dgcon_rt_dr.*dlambda_dr.*dlambda_dt+dgcon_tt_dr.*(I1+dlambda_dt) ...
.^2+2.*dgcon_rz_dr.*dlambda_dr.*dlambda_dz+2.*dgcon_tz_dr.*(I1+ ...
dlambda_dt).*dlambda_dz+dgcon_zz_dr.*dlambda_dz.^2+2.*dlambda_dr.* ...
dlambda_dr2.*gcon_rr+2.*dlambda_dr2.*gcon_rt+2.*dlambda_dr.* ...
dlambda_drdt.*gcon_rt+2.*dlambda_dr2.*dlambda_dt.*gcon_rt+2.* ...
dlambda_dr.*dlambda_drdz.*gcon_rz+2.*dlambda_dr2.*dlambda_dz.* ...
gcon_rz+2.*dlambda_drdt.*(I1+dlambda_dt).*gcon_tt+2.*dlambda_drdz.* ...
(I1+dlambda_dt).*gcon_tz+2.*dlambda_drdt.*dlambda_dz.*gcon_tz+2.* ...
dlambda_drdz.*dlambda_dz.*gcon_zz+(-1).*dlambda_dr.*(I1+dlambda_dt) ...
.^(-1).*(2.*dgcon_rt_dt.*dlambda_dr+dgcon_rr_dt.*dlambda_dr.^2+2.* ...
dgcon_rt_dt.*dlambda_dr.*dlambda_dt+dgcon_tt_dt.*(I1+dlambda_dt) ...
.^2+dgcon_zz_dt.*dlambda_dz.^2+2.*dlambda_dr.*dlambda_drdt.* ...
gcon_rr+2.*dlambda_drdt.*gcon_rt+2.*dlambda_drdt.*dlambda_dt.* ...
gcon_rt+2.*dlambda_dr.*dlambda_dt2.*gcon_rt+2.*dlambda_dr.* ...
dlambda_dtdz.*gcon_rz+2.*dlambda_dt2.*gcon_tt+2.*dlambda_dt.* ...
dlambda_dt2.*gcon_tt+2.*dlambda_dtdz.*gcon_tz+2.*dlambda_dt.* ...
dlambda_dtdz.*gcon_tz+2.*dlambda_dz.*(dgcon_rz_dt.*dlambda_dr+ ...
dgcon_tz_dt.*(I1+dlambda_dt)+dlambda_drdt.*gcon_rz+dlambda_dt2.* ...
gcon_tz+dlambda_dtdz.*gcon_zz));
dgcon_rz_dr.*dlambda_dr+dgcon_tz_dr.*(I1+dlambda_dt)+dgcon_zz_dr.* ...
dlambda_dz+dlambda_dr2.*gcon_rz+dlambda_drdt.*gcon_tz+ ...
dlambda_drdz.*gcon_zz+(-1).*dlambda_dr.*(I1+dlambda_dt).^(-1).*( ...
dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dgcon_zz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rz+dlambda_dt2.*gcon_tz+ ...
dlambda_dtdz.*gcon_zz);
dgcon_rz_dr+(-1).*dgcon_rz_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1);
dgcon_rz_dr.*dlambda_dr+dgcon_tz_dr.*(I1+dlambda_dt)+dgcon_zz_dr.* ...
dlambda_dz+dlambda_dr2.*gcon_rz+dlambda_drdt.*gcon_tz+ ...
dlambda_drdz.*gcon_zz+(-1).*dlambda_dr.*(I1+dlambda_dt).^(-1).*( ...
dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dgcon_zz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rz+dlambda_dt2.*gcon_tz+ ...
dlambda_dtdz.*gcon_zz);
dgcon_zz_dr+(-1).*dgcon_zz_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1);
},3,3);


dgconPEST_dtheta=reshape({dgcon_rr_dt.*(I1+dlambda_dt).^(-1);
(I1+dlambda_dt).^(-1).*(dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+ ...
dlambda_dt)+dgcon_rz_dt.*dlambda_dz+dlambda_drdt.*gcon_rr+ ...
dlambda_dt2.*gcon_rt+dlambda_dtdz.*gcon_rz);
dgcon_rz_dt.*(I1+dlambda_dt).^(-1);
(I1+dlambda_dt).^(-1).*(dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+ ...
dlambda_dt)+dgcon_rz_dt.*dlambda_dz+dlambda_drdt.*gcon_rr+ ...
dlambda_dt2.*gcon_rt+dlambda_dtdz.*gcon_rz);
(I1+dlambda_dt).^(-1).*(2.*dgcon_rt_dt.*dlambda_dr+dgcon_rr_dt.* ...
dlambda_dr.^2+2.*dgcon_rt_dt.*dlambda_dr.*dlambda_dt+dgcon_tt_dt.* ...
(I1+dlambda_dt).^2+dgcon_zz_dt.*dlambda_dz.^2+2.*dlambda_dr.* ...
dlambda_drdt.*gcon_rr+2.*dlambda_drdt.*gcon_rt+2.*dlambda_drdt.* ...
dlambda_dt.*gcon_rt+2.*dlambda_dr.*dlambda_dt2.*gcon_rt+2.* ...
dlambda_dr.*dlambda_dtdz.*gcon_rz+2.*dlambda_dt2.*gcon_tt+2.* ...
dlambda_dt.*dlambda_dt2.*gcon_tt+2.*dlambda_dtdz.*gcon_tz+2.* ...
dlambda_dt.*dlambda_dtdz.*gcon_tz+2.*dlambda_dz.*(dgcon_rz_dt.* ...
dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dlambda_drdt.*gcon_rz+ ...
dlambda_dt2.*gcon_tz+dlambda_dtdz.*gcon_zz));
(I1+dlambda_dt).^(-1).*(dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+ ...
dlambda_dt)+dgcon_zz_dt.*dlambda_dz+dlambda_drdt.*gcon_rz+ ...
dlambda_dt2.*gcon_tz+dlambda_dtdz.*gcon_zz);
dgcon_rz_dt.*(I1+dlambda_dt).^(-1);
(I1+dlambda_dt).^(-1).*(dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+ ...
dlambda_dt)+dgcon_zz_dt.*dlambda_dz+dlambda_drdt.*gcon_rz+ ...
dlambda_dt2.*gcon_tz+dlambda_dtdz.*gcon_zz);
dgcon_zz_dt.*(I1+dlambda_dt).^(-1);
},3,3);


dgconPEST_dphi=reshape({dgcon_rr_dz+(-1).*dgcon_rr_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz;
dgcon_rr_dz.*dlambda_dr+dgcon_rt_dz.*(I1+dlambda_dt)+dgcon_rz_dz.* ...
dlambda_dz+dlambda_drdz.*gcon_rr+dlambda_dtdz.*gcon_rt+ ...
dlambda_dz2.*gcon_rz+(-1).*(I1+dlambda_dt).^(-1).*dlambda_dz.*( ...
dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+dlambda_dt)+dgcon_rz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rr+dlambda_dt2.*gcon_rt+ ...
dlambda_dtdz.*gcon_rz);
dgcon_rz_dz+(-1).*dgcon_rz_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz;
dgcon_rr_dz.*dlambda_dr+dgcon_rt_dz.*(I1+dlambda_dt)+dgcon_rz_dz.* ...
dlambda_dz+dlambda_drdz.*gcon_rr+dlambda_dtdz.*gcon_rt+ ...
dlambda_dz2.*gcon_rz+(-1).*(I1+dlambda_dt).^(-1).*dlambda_dz.*( ...
dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+dlambda_dt)+dgcon_rz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rr+dlambda_dt2.*gcon_rt+ ...
dlambda_dtdz.*gcon_rz);
2.*dgcon_rt_dz.*dlambda_dr+dgcon_rr_dz.*dlambda_dr.^2+2.* ...
dgcon_rt_dz.*dlambda_dr.*dlambda_dt+dgcon_tt_dz.*(I1+dlambda_dt) ...
.^2+2.*dgcon_rz_dz.*dlambda_dr.*dlambda_dz+2.*dgcon_tz_dz.*(I1+ ...
dlambda_dt).*dlambda_dz+dgcon_zz_dz.*dlambda_dz.^2+2.*dlambda_dr.* ...
dlambda_drdz.*gcon_rr+2.*dlambda_drdz.*gcon_rt+2.*dlambda_drdz.* ...
dlambda_dt.*gcon_rt+2.*dlambda_dr.*dlambda_dtdz.*gcon_rt+2.* ...
dlambda_drdz.*dlambda_dz.*gcon_rz+2.*dlambda_dr.*dlambda_dz2.* ...
gcon_rz+2.*(I1+dlambda_dt).*dlambda_dtdz.*gcon_tt+2.*dlambda_dtdz.* ...
dlambda_dz.*gcon_tz+2.*(I1+dlambda_dt).*dlambda_dz2.*gcon_tz+2.* ...
dlambda_dz.*dlambda_dz2.*gcon_zz+(-1).*(I1+dlambda_dt).^(-1).* ...
dlambda_dz.*(2.*dgcon_rt_dt.*dlambda_dr+dgcon_rr_dt.* ...
dlambda_dr.^2+2.*dgcon_rt_dt.*dlambda_dr.*dlambda_dt+dgcon_tt_dt.* ...
(I1+dlambda_dt).^2+dgcon_zz_dt.*dlambda_dz.^2+2.*dlambda_dr.* ...
dlambda_drdt.*gcon_rr+2.*dlambda_drdt.*gcon_rt+2.*dlambda_drdt.* ...
dlambda_dt.*gcon_rt+2.*dlambda_dr.*dlambda_dt2.*gcon_rt+2.* ...
dlambda_dr.*dlambda_dtdz.*gcon_rz+2.*dlambda_dt2.*gcon_tt+2.* ...
dlambda_dt.*dlambda_dt2.*gcon_tt+2.*dlambda_dtdz.*gcon_tz+2.* ...
dlambda_dt.*dlambda_dtdz.*gcon_tz+2.*dlambda_dz.*(dgcon_rz_dt.* ...
dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dlambda_drdt.*gcon_rz+ ...
dlambda_dt2.*gcon_tz+dlambda_dtdz.*gcon_zz));
dgcon_rz_dz.*dlambda_dr+dgcon_tz_dz.*(I1+dlambda_dt)+dgcon_zz_dz.* ...
dlambda_dz+dlambda_drdz.*gcon_rz+dlambda_dtdz.*gcon_tz+ ...
dlambda_dz2.*gcon_zz+(-1).*(I1+dlambda_dt).^(-1).*dlambda_dz.*( ...
dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dgcon_zz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rz+dlambda_dt2.*gcon_tz+ ...
dlambda_dtdz.*gcon_zz);
dgcon_rz_dz+(-1).*dgcon_rz_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz;
dgcon_rz_dz.*dlambda_dr+dgcon_tz_dz.*(I1+dlambda_dt)+dgcon_zz_dz.* ...
dlambda_dz+dlambda_drdz.*gcon_rz+dlambda_dtdz.*gcon_tz+ ...
dlambda_dz2.*gcon_zz+(-1).*(I1+dlambda_dt).^(-1).*dlambda_dz.*( ...
dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dgcon_zz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rz+dlambda_dt2.*gcon_tz+ ...
dlambda_dtdz.*gcon_zz);
dgcon_zz_dz+(-1).*dgcon_zz_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz;
},3,3);


gcovPEST=reshape({gcov_rr+dlambda_dr.*(I1+dlambda_dt).^(-2).*((-2).*(I1+dlambda_dt).* ...
gcov_rt+dlambda_dr.*gcov_tt);
(I1+dlambda_dt).^(-2).*((I1+dlambda_dt).*gcov_rt+(-1).*dlambda_dr.* ...
gcov_tt);
gcov_rz+(-1).*(I1+dlambda_dt).^(-2).*((I1+dlambda_dt).*dlambda_dz.* ...
gcov_rt+dlambda_dr.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz));
(I1+dlambda_dt).^(-2).*((I1+dlambda_dt).*gcov_rt+(-1).*dlambda_dr.* ...
gcov_tt);
(I1+dlambda_dt).^(-2).*gcov_tt;
(I1+dlambda_dt).^(-2).*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz);
gcov_rz+(-1).*(I1+dlambda_dt).^(-2).*((I1+dlambda_dt).*dlambda_dz.* ...
gcov_rt+dlambda_dr.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz));
(I1+dlambda_dt).^(-2).*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz);
(I1+dlambda_dt).^(-2).*dlambda_dz.*(dlambda_dz.*gcov_tt+(-2).*(I1+ ...
dlambda_dt).*gcov_tz)+gcov_zz;
},3,3);


dgcovPEST_drho=reshape({dgcov_rr_dr+dgcov_tt_dr.*dlambda_dr.^2.*(I1+dlambda_dt).^(-2)+(-1) ...
.*dgcov_rr_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1)+(-2).* ...
dgcov_rt_dr.*dlambda_dr.*(I1+dlambda_dt).^(-1)+2.*dlambda_dr.* ...
dlambda_drdt.*(I1+dlambda_dt).^(-2).*gcov_rt+(-2).*dlambda_dr2.*(I1+ ...
dlambda_dt).^(-1).*gcov_rt+(-2).*dlambda_dr.^2.*dlambda_drdt.*(I1+ ...
dlambda_dt).^(-3).*gcov_tt+2.*dlambda_dr.*dlambda_dr2.*(I1+ ...
dlambda_dt).^(-2).*gcov_tt+dlambda_dr.*(I1+dlambda_dt).^(-4).*(2.* ...
dgcov_rt_dt.*dlambda_dr.*(I1+dlambda_dt).^2+2.*(I1+dlambda_dt).*( ...
dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_rt+(-1).*dlambda_dr.*(dgcov_tt_dt.*dlambda_dr.*(I1+dlambda_dt) ...
+2.*(dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_tt));
(I1+dlambda_dt).^(-3).*((-2).*dlambda_drdt.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dr.*dlambda_dr+dgcov_rt_dr.*(I1+dlambda_dt)+dlambda_drdt.* ...
gcov_rt+(-1).*dlambda_dr2.*gcov_tt)+dlambda_dr.*(dgcov_tt_dt.* ...
dlambda_dr+(-1).*dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.*gcov_rt+ ...
dlambda_drdt.*gcov_tt+(-2).*dlambda_dr.*(I1+dlambda_dt).^(-1).* ...
dlambda_dt2.*gcov_tt));
dgcov_rz_dr+(-1).*(I1+dlambda_dt).^(-2).*(dlambda_dz.*((-1).* ...
dgcov_tt_dr.*dlambda_dr+dgcov_rt_dr.*(I1+dlambda_dt)+dlambda_drdt.* ...
gcov_rt+(-1).*dlambda_dr2.*gcov_tt)+(I1+dlambda_dt).*( ...
dlambda_drdz.*gcov_rt+dlambda_dr2.*gcov_tz)+dlambda_dr.*( ...
dgcov_tz_dr.*(I1+dlambda_dt)+(-1).*dlambda_drdz.*gcov_tt+ ...
dlambda_drdt.*gcov_tz))+2.*dlambda_drdt.*(I1+dlambda_dt).^(-3).*(( ...
I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.* ...
gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*dlambda_dr.*(I1+dlambda_dt) ...
.^(-1).*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).*dlambda_dt2.*((I1+ ...
dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.* ...
gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+dlambda_dt).^(-2).*( ...
dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+dlambda_dt).* ...
dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.*gcov_rt+ ...
dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+ ...
dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dgcov_tt_dt.* ...
dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.*gcov_tz)));
(I1+dlambda_dt).^(-3).*((-2).*dlambda_drdt.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dr.*dlambda_dr+dgcov_rt_dr.*(I1+dlambda_dt)+dlambda_drdt.* ...
gcov_rt+(-1).*dlambda_dr2.*gcov_tt)+dlambda_dr.*(dgcov_tt_dt.* ...
dlambda_dr+(-1).*dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.*gcov_rt+ ...
dlambda_drdt.*gcov_tt+(-2).*dlambda_dr.*(I1+dlambda_dt).^(-1).* ...
dlambda_dt2.*gcov_tt));
(I1+dlambda_dt).^(-4).*((-1).*dgcov_tt_dt.*dlambda_dr.*(I1+ ...
dlambda_dt)+dgcov_tt_dr.*(I1+dlambda_dt).^2+2.*((-1).* ...
dlambda_drdt.*(I1+dlambda_dt)+dlambda_dr.*dlambda_dt2).*gcov_tt);
(I1+dlambda_dt).^(-3).*((I1+dlambda_dt).*(dgcov_tz_dr.*(I1+ ...
dlambda_dt)+(-1).*dgcov_tt_dr.*dlambda_dz+(-1).*dlambda_drdz.* ...
gcov_tt+dlambda_drdt.*gcov_tz)+(-2).*dlambda_drdt.*((-1).* ...
dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+dlambda_dr.*((-1).* ...
dgcov_tz_dt.*(I1+dlambda_dt)+dlambda_dtdz.*gcov_tt+dlambda_dz.*( ...
dgcov_tt_dt+(-2).*(I1+dlambda_dt).^(-1).*dlambda_dt2.*gcov_tt)+ ...
dlambda_dt2.*gcov_tz));
dgcov_rz_dr+(-1).*(I1+dlambda_dt).^(-2).*(dlambda_dz.*((-1).* ...
dgcov_tt_dr.*dlambda_dr+dgcov_rt_dr.*(I1+dlambda_dt)+dlambda_drdt.* ...
gcov_rt+(-1).*dlambda_dr2.*gcov_tt)+(I1+dlambda_dt).*( ...
dlambda_drdz.*gcov_rt+dlambda_dr2.*gcov_tz)+dlambda_dr.*( ...
dgcov_tz_dr.*(I1+dlambda_dt)+(-1).*dlambda_drdz.*gcov_tt+ ...
dlambda_drdt.*gcov_tz))+2.*dlambda_drdt.*(I1+dlambda_dt).^(-3).*(( ...
I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.* ...
gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*dlambda_dr.*(I1+dlambda_dt) ...
.^(-1).*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).*dlambda_dt2.*((I1+ ...
dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.* ...
gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+dlambda_dt).^(-2).*( ...
dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+dlambda_dt).* ...
dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.*gcov_rt+ ...
dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+ ...
dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dgcov_tt_dt.* ...
dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.*gcov_tz)));
(I1+dlambda_dt).^(-3).*((I1+dlambda_dt).*(dgcov_tz_dr.*(I1+ ...
dlambda_dt)+(-1).*dgcov_tt_dr.*dlambda_dz+(-1).*dlambda_drdz.* ...
gcov_tt+dlambda_drdt.*gcov_tz)+(-2).*dlambda_drdt.*((-1).* ...
dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+dlambda_dr.*((-1).* ...
dgcov_tz_dt.*(I1+dlambda_dt)+dlambda_dtdz.*gcov_tt+dlambda_dz.*( ...
dgcov_tt_dt+(-2).*(I1+dlambda_dt).^(-1).*dlambda_dt2.*gcov_tt)+ ...
dlambda_dt2.*gcov_tz));
dgcov_zz_dr+(I1+dlambda_dt).^(-2).*dlambda_dz.*((-2).*dgcov_tz_dr.* ...
(I1+dlambda_dt)+dgcov_tt_dr.*dlambda_dz+dlambda_drdz.*gcov_tt+(-2) ...
.*dlambda_drdt.*gcov_tz)+dlambda_drdz.*(I1+dlambda_dt).^(-2).*( ...
dlambda_dz.*gcov_tt+(-2).*(I1+dlambda_dt).*gcov_tz)+(-2).* ...
dlambda_drdt.*(I1+dlambda_dt).^(-3).*dlambda_dz.*(dlambda_dz.* ...
gcov_tt+(-2).*(I1+dlambda_dt).*gcov_tz)+(-1).*dlambda_dr.*(I1+ ...
dlambda_dt).^(-4).*(dlambda_dz.^2.*(dgcov_tt_dt.*(I1+dlambda_dt)+( ...
-2).*dlambda_dt2.*gcov_tt)+(-2).*(I1+dlambda_dt).*dlambda_dz.*( ...
dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dlambda_dtdz.*gcov_tt+(-1).* ...
dlambda_dt2.*gcov_tz)+(I1+dlambda_dt).^2.*(dgcov_zz_dt.*(I1+ ...
dlambda_dt)+(-2).*dlambda_dtdz.*gcov_tz));
},3,3);


dgcovPEST_dtheta=reshape({(I1+dlambda_dt).^(-1).*(dgcov_rr_dt+(I1+dlambda_dt).^(-3).*((-2).* ...
dgcov_rt_dt.*dlambda_dr.*(I1+dlambda_dt).^2+(-2).*(I1+dlambda_dt).*( ...
dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_rt+dlambda_dr.*(dgcov_tt_dt.*dlambda_dr.*(I1+dlambda_dt)+2.*( ...
dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_tt)));
(I1+dlambda_dt).^(-4).*((-2).*dlambda_dt2.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dt.*dlambda_dr+dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.* ...
gcov_rt+(-1).*dlambda_drdt.*gcov_tt));
(I1+dlambda_dt).^(-1).*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*(( ...
-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+ ...
dlambda_dt).^(-2).*(dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+ ...
dlambda_dt).*dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.* ...
gcov_rt+dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz)+dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).* ...
dgcov_tt_dt.*dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.* ...
gcov_tz)));
(I1+dlambda_dt).^(-4).*((-2).*dlambda_dt2.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dt.*dlambda_dr+dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.* ...
gcov_rt+(-1).*dlambda_drdt.*gcov_tt));
(I1+dlambda_dt).^(-4).*(dgcov_tt_dt.*(I1+dlambda_dt)+(-2).* ...
dlambda_dt2.*gcov_tt);
(I1+dlambda_dt).^(-4).*((-1).*dlambda_dz.*(dgcov_tt_dt.*(I1+ ...
dlambda_dt)+(-2).*dlambda_dt2.*gcov_tt)+(I1+dlambda_dt).*( ...
dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dlambda_dtdz.*gcov_tt+(-1).* ...
dlambda_dt2.*gcov_tz));
(I1+dlambda_dt).^(-1).*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*(( ...
-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+ ...
dlambda_dt).^(-2).*(dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+ ...
dlambda_dt).*dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.* ...
gcov_rt+dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz)+dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).* ...
dgcov_tt_dt.*dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.* ...
gcov_tz)));
(I1+dlambda_dt).^(-4).*((-1).*dlambda_dz.*(dgcov_tt_dt.*(I1+ ...
dlambda_dt)+(-2).*dlambda_dt2.*gcov_tt)+(I1+dlambda_dt).*( ...
dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dlambda_dtdz.*gcov_tt+(-1).* ...
dlambda_dt2.*gcov_tz));
(I1+dlambda_dt).^(-4).*(dlambda_dz.^2.*(dgcov_tt_dt.*(I1+dlambda_dt) ...
+(-2).*dlambda_dt2.*gcov_tt)+(-2).*(I1+dlambda_dt).*dlambda_dz.*( ...
dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dlambda_dtdz.*gcov_tt+(-1).* ...
dlambda_dt2.*gcov_tz)+(I1+dlambda_dt).^2.*(dgcov_zz_dt.*(I1+ ...
dlambda_dt)+(-2).*dlambda_dtdz.*gcov_tz));
},3,3);


dgcovPEST_dphi=reshape({dgcov_rr_dz+dgcov_tt_dz.*dlambda_dr.^2.*(I1+dlambda_dt).^(-2)+(-2) ...
.*dgcov_rt_dz.*dlambda_dr.*(I1+dlambda_dt).^(-1)+(-1).* ...
dgcov_rr_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz+(-2).*dlambda_drdz.* ...
(I1+dlambda_dt).^(-1).*gcov_rt+2.*dlambda_dr.*(I1+dlambda_dt).^(-2) ...
.*dlambda_dtdz.*gcov_rt+2.*dlambda_dr.*dlambda_drdz.*(I1+ ...
dlambda_dt).^(-2).*gcov_tt+(-2).*dlambda_dr.^2.*(I1+dlambda_dt).^( ...
-3).*dlambda_dtdz.*gcov_tt+(I1+dlambda_dt).^(-4).*dlambda_dz.*(2.* ...
dgcov_rt_dt.*dlambda_dr.*(I1+dlambda_dt).^2+2.*(I1+dlambda_dt).*( ...
dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_rt+(-1).*dlambda_dr.*(dgcov_tt_dt.*dlambda_dr.*(I1+dlambda_dt) ...
+2.*(dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_tt));
(I1+dlambda_dt).^(-3).*((-2).*dlambda_dtdz.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dz.*dlambda_dr+dgcov_rt_dz.*(I1+dlambda_dt)+dlambda_dtdz.* ...
gcov_rt+(-1).*dlambda_drdz.*gcov_tt)+dlambda_dz.*(dgcov_tt_dt.* ...
dlambda_dr+(-1).*dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.*gcov_rt+ ...
dlambda_drdt.*gcov_tt+(-2).*dlambda_dr.*(I1+dlambda_dt).^(-1).* ...
dlambda_dt2.*gcov_tt));
dgcov_rz_dz+2.*(I1+dlambda_dt).^(-3).*dlambda_dtdz.*((I1+dlambda_dt) ...
.*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.*gcov_tt+(I1+ ...
dlambda_dt).*gcov_tz))+(-1).*(I1+dlambda_dt).^(-2).*(dgcov_rt_dz.*( ...
I1+dlambda_dt).*dlambda_dz+dlambda_dtdz.*dlambda_dz.*gcov_rt+(I1+ ...
dlambda_dt).*dlambda_dz2.*gcov_rt+dlambda_drdz.*((-1).* ...
dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+dlambda_dr.*( ...
dgcov_tz_dz.*(I1+dlambda_dt)+(-1).*dgcov_tt_dz.*dlambda_dz+(-1).* ...
dlambda_dz2.*gcov_tt+dlambda_dtdz.*gcov_tz))+(-1).*(I1+dlambda_dt) ...
.^(-1).*dlambda_dz.*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*(( ...
-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+ ...
dlambda_dt).^(-2).*(dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+ ...
dlambda_dt).*dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.* ...
gcov_rt+dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz)+dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).* ...
dgcov_tt_dt.*dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.* ...
gcov_tz)));
(I1+dlambda_dt).^(-3).*((-2).*dlambda_dtdz.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dz.*dlambda_dr+dgcov_rt_dz.*(I1+dlambda_dt)+dlambda_dtdz.* ...
gcov_rt+(-1).*dlambda_drdz.*gcov_tt)+dlambda_dz.*(dgcov_tt_dt.* ...
dlambda_dr+(-1).*dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.*gcov_rt+ ...
dlambda_drdt.*gcov_tt+(-2).*dlambda_dr.*(I1+dlambda_dt).^(-1).* ...
dlambda_dt2.*gcov_tt));
(I1+dlambda_dt).^(-4).*(dgcov_tt_dz.*(I1+dlambda_dt).^2+(-2).*(I1+ ...
dlambda_dt).*dlambda_dtdz.*gcov_tt+(-1).*dlambda_dz.*( ...
dgcov_tt_dt.*(I1+dlambda_dt)+(-2).*dlambda_dt2.*gcov_tt));
(I1+dlambda_dt).^(-4).*(dlambda_dz.^2.*(dgcov_tt_dt.*(I1+dlambda_dt) ...
+(-2).*dlambda_dt2.*gcov_tt)+(-1).*(I1+dlambda_dt).*dlambda_dz.*( ...
dgcov_tt_dz.*(I1+dlambda_dt)+dgcov_tz_dt.*(I1+dlambda_dt)+(-3).* ...
dlambda_dtdz.*gcov_tt+(-1).*dlambda_dt2.*gcov_tz)+(I1+dlambda_dt) ...
.^2.*(dgcov_tz_dz.*(I1+dlambda_dt)+(-1).*dlambda_dz2.*gcov_tt+(-1) ...
.*dlambda_dtdz.*gcov_tz));
dgcov_rz_dz+2.*(I1+dlambda_dt).^(-3).*dlambda_dtdz.*((I1+dlambda_dt) ...
.*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.*gcov_tt+(I1+ ...
dlambda_dt).*gcov_tz))+(-1).*(I1+dlambda_dt).^(-2).*(dgcov_rt_dz.*( ...
I1+dlambda_dt).*dlambda_dz+dlambda_dtdz.*dlambda_dz.*gcov_rt+(I1+ ...
dlambda_dt).*dlambda_dz2.*gcov_rt+dlambda_drdz.*((-1).* ...
dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+dlambda_dr.*( ...
dgcov_tz_dz.*(I1+dlambda_dt)+(-1).*dgcov_tt_dz.*dlambda_dz+(-1).* ...
dlambda_dz2.*gcov_tt+dlambda_dtdz.*gcov_tz))+(-1).*(I1+dlambda_dt) ...
.^(-1).*dlambda_dz.*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*(( ...
-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+ ...
dlambda_dt).^(-2).*(dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+ ...
dlambda_dt).*dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.* ...
gcov_rt+dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz)+dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).* ...
dgcov_tt_dt.*dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.* ...
gcov_tz)));
(I1+dlambda_dt).^(-4).*(dlambda_dz.^2.*(dgcov_tt_dt.*(I1+dlambda_dt) ...
+(-2).*dlambda_dt2.*gcov_tt)+(-1).*(I1+dlambda_dt).*dlambda_dz.*( ...
dgcov_tt_dz.*(I1+dlambda_dt)+dgcov_tz_dt.*(I1+dlambda_dt)+(-3).* ...
dlambda_dtdz.*gcov_tt+(-1).*dlambda_dt2.*gcov_tz)+(I1+dlambda_dt) ...
.^2.*(dgcov_tz_dz.*(I1+dlambda_dt)+(-1).*dlambda_dz2.*gcov_tt+(-1) ...
.*dlambda_dtdz.*gcov_tz));
(I1+dlambda_dt).^(-4).*(dgcov_zz_dz.*(I1+dlambda_dt).^4+(-2).* ...
dgcov_tz_dz.*(I1+dlambda_dt).^3.*dlambda_dz+(-1).*dgcov_zz_dt.*(I1+ ...
dlambda_dt).^3.*dlambda_dz+dgcov_tt_dz.*(I1+dlambda_dt).^2.* ...
dlambda_dz.^2+2.*dgcov_tz_dt.*(I1+dlambda_dt).^2.*dlambda_dz.^2+( ...
-1).*dgcov_tt_dt.*(I1+dlambda_dt).*dlambda_dz.^3+(-4).*(I1+ ...
dlambda_dt).*dlambda_dtdz.*dlambda_dz.^2.*gcov_tt+2.*dlambda_dt2.* ...
dlambda_dz.^3.*gcov_tt+2.*(I1+dlambda_dt).^2.*dlambda_dz.* ...
dlambda_dz2.*gcov_tt+4.*(I1+dlambda_dt).^2.*dlambda_dtdz.* ...
dlambda_dz.*gcov_tz+(-2).*(I1+dlambda_dt).*dlambda_dt2.* ...
dlambda_dz.^2.*gcov_tz+(-2).*(I1+dlambda_dt).^3.*dlambda_dz2.* ...
gcov_tz);
},3,3);


%% PEST Jacobian

Jpest=((I1+dlambda_dt).^(-2).*((-1).*gcov_rz.^2.*gcov_tt+2.*gcov_rt.* ...
gcov_rz.*gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).* ...
gcov_tz.^2+gcov_tt.*gcov_zz))).^(1/2);


dJpest_drho=(1/2).*((I1+dlambda_dt).^(-2).*((-1).*gcov_rz.^2.*gcov_tt+2.* ...
gcov_rt.*gcov_rz.*gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1) ...
.*gcov_tz.^2+gcov_tt.*gcov_zz))).^(-1/2).*((I1+dlambda_dt).^(-2).*( ...
(-1).*dgcov_zz_dr.*gcov_rt.^2+2.*dgcov_tz_dr.*gcov_rt.*gcov_rz+( ...
-1).*dgcov_tt_dr.*gcov_rz.^2+(-2).*dgcov_rz_dr.*gcov_rz.*gcov_tt+ ...
2.*dgcov_rz_dr.*gcov_rt.*gcov_tz+2.*dgcov_rt_dr.*gcov_rz.*gcov_tz+ ...
(-2).*dgcov_rt_dr.*gcov_rt.*gcov_zz+gcov_rr.*(dgcov_zz_dr.* ...
gcov_tt+(-2).*dgcov_tz_dr.*gcov_tz+dgcov_tt_dr.*gcov_zz)+ ...
dgcov_rr_dr.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))+(-2).* ...
dlambda_drdt.*(I1+dlambda_dt).^(-3).*((-1).*gcov_rz.^2.*gcov_tt+2.* ...
gcov_rt.*gcov_rz.*gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1) ...
.*gcov_tz.^2+gcov_tt.*gcov_zz)))+(-1/2).*dlambda_dr.*(I1+ ...
dlambda_dt).^(-1).*((I1+dlambda_dt).^(-2).*((-1).*gcov_rz.^2.* ...
gcov_tt+2.*gcov_rt.*gcov_rz.*gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+ ...
gcov_rr.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))).^(-1/2).*((I1+ ...
dlambda_dt).^(-2).*((-1).*dgcov_zz_dt.*gcov_rt.^2+2.*dgcov_tz_dt.* ...
gcov_rt.*gcov_rz+(-1).*dgcov_tt_dt.*gcov_rz.^2+(-2).*dgcov_rz_dt.* ...
gcov_rz.*gcov_tt+2.*dgcov_rz_dt.*gcov_rt.*gcov_tz+2.*dgcov_rt_dt.* ...
gcov_rz.*gcov_tz+(-2).*dgcov_rt_dt.*gcov_rt.*gcov_zz+gcov_rr.*( ...
dgcov_zz_dt.*gcov_tt+(-2).*dgcov_tz_dt.*gcov_tz+dgcov_tt_dt.* ...
gcov_zz)+dgcov_rr_dt.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))+(-2).*( ...
I1+dlambda_dt).^(-3).*dlambda_dt2.*((-1).*gcov_rz.^2.*gcov_tt+2.* ...
gcov_rt.*gcov_rz.*gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1) ...
.*gcov_tz.^2+gcov_tt.*gcov_zz)));


dJpest_dtheta=(1/2).*(I1+dlambda_dt).^(-1).*((I1+dlambda_dt).^(-2).*((-1).* ...
gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.*gcov_tz+(-1).* ...
gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))) ...
.^(-1/2).*((I1+dlambda_dt).^(-2).*((-1).*dgcov_zz_dt.*gcov_rt.^2+ ...
2.*dgcov_tz_dt.*gcov_rt.*gcov_rz+(-1).*dgcov_tt_dt.*gcov_rz.^2+( ...
-2).*dgcov_rz_dt.*gcov_rz.*gcov_tt+2.*dgcov_rz_dt.*gcov_rt.* ...
gcov_tz+2.*dgcov_rt_dt.*gcov_rz.*gcov_tz+(-2).*dgcov_rt_dt.* ...
gcov_rt.*gcov_zz+gcov_rr.*(dgcov_zz_dt.*gcov_tt+(-2).* ...
dgcov_tz_dt.*gcov_tz+dgcov_tt_dt.*gcov_zz)+dgcov_rr_dt.*((-1).* ...
gcov_tz.^2+gcov_tt.*gcov_zz))+(-2).*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((-1).*gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.* ...
gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+ ...
gcov_tt.*gcov_zz)));


dJpest_dphi=(-1/2).*(I1+dlambda_dt).^(-1).*dlambda_dz.*((I1+dlambda_dt).^(-2).*( ...
(-1).*gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.*gcov_tz+(-1).* ...
gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))) ...
.^(-1/2).*((I1+dlambda_dt).^(-2).*((-1).*dgcov_zz_dt.*gcov_rt.^2+ ...
2.*dgcov_tz_dt.*gcov_rt.*gcov_rz+(-1).*dgcov_tt_dt.*gcov_rz.^2+( ...
-2).*dgcov_rz_dt.*gcov_rz.*gcov_tt+2.*dgcov_rz_dt.*gcov_rt.* ...
gcov_tz+2.*dgcov_rt_dt.*gcov_rz.*gcov_tz+(-2).*dgcov_rt_dt.* ...
gcov_rt.*gcov_zz+gcov_rr.*(dgcov_zz_dt.*gcov_tt+(-2).* ...
dgcov_tz_dt.*gcov_tz+dgcov_tt_dt.*gcov_zz)+dgcov_rr_dt.*((-1).* ...
gcov_tz.^2+gcov_tt.*gcov_zz))+(-2).*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((-1).*gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.* ...
gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+ ...
gcov_tt.*gcov_zz)))+(1/2).*((I1+dlambda_dt).^(-2).*((-1).* ...
gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.*gcov_tz+(-1).* ...
gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))) ...
.^(-1/2).*((I1+dlambda_dt).^(-2).*((-1).*dgcov_zz_dz.*gcov_rt.^2+ ...
2.*dgcov_tz_dz.*gcov_rt.*gcov_rz+(-1).*dgcov_tt_dz.*gcov_rz.^2+( ...
-2).*dgcov_rz_dz.*gcov_rz.*gcov_tt+2.*dgcov_rz_dz.*gcov_rt.* ...
gcov_tz+2.*dgcov_rt_dz.*gcov_rz.*gcov_tz+(-2).*dgcov_rt_dz.* ...
gcov_rt.*gcov_zz+gcov_rr.*(dgcov_zz_dz.*gcov_tt+(-2).* ...
dgcov_tz_dz.*gcov_tz+dgcov_tt_dz.*gcov_zz)+dgcov_rr_dz.*((-1).* ...
gcov_tz.^2+gcov_tt.*gcov_zz))+(-2).*(I1+dlambda_dt).^(-3).* ...
dlambda_dtdz.*((-1).*gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.* ...
gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+ ...
gcov_tt.*gcov_zz)));

%% Jpara/B

[jp,djp_drho,djp_dtheta,djp_dphi] = interp_3d_d1_(J_parallel);

plotCompare3D_(J_parallel,jp,'Jpara');

jp_B = jp./B;
djp_B_drho = (djp_drho.*B-dB_drho.*jp)./B.^2;
djp_B_dtheta = (djp_dtheta.*B-dB_dtheta.*jp)./B.^2;
djp_B_dphi = (djp_dphi.*B-dB_dphi.*jp)./B.^2;

plotFields3D_({jp,djp_drho,djp_dtheta,djp_dphi}, ...
    {'Jpara','dJpara/drho','dJpara/dtheta','dJpara/dphi'}, ...
    'Jpara',1);


%% Compare PEST Metric and Jacobian

metric_names = ["xx","xy","xz","yy","yz","zz"];
metric_i = [1,1,1,2,2,3];
metric_j = [1,2,3,2,3,3];
vars = ["rho","theta","phi"];
direct_vars = ["px","py","pz"];

for n = 1:numel(metric_names)
    name = char(metric_names(n));
    i = metric_i(n);
    j = metric_j(n);

    direct = eval(['PESTcon_',name]);
    transform = gconPEST{i,j};
    plotCompare3D_(direct,transform,['PESTcon_',name]);

    direct = eval(['PESTcov_',name]);
    transform = gcovPEST{i,j};
    plotCompare3D_(direct,transform,['PESTcov_',name]);

    for k = 1:numel(vars)
        direct = eval(['dPESTcon_',name,'_',char(direct_vars(k))]);
        transform = eval(['dgconPEST_d',char(vars(k)),'{',num2str(i),',',num2str(j),'}']);
        plotCompare3D_(direct,transform,['dPESTcon_',name,'_',char(direct_vars(k))]);

        direct = eval(['dPESTcov_',name,'_',char(direct_vars(k))]);
        transform = eval(['dgcovPEST_d',char(vars(k)),'{',num2str(i),',',num2str(j),'}']);
        plotCompare3D_(direct,transform,['dPESTcov_',name,'_',char(direct_vars(k))]);
    end
end

plotCompare3D_(JPEST,Jpest,'JPEST');
plotCompare3D_(dJPEST_drho,dJpest_drho,'dJPEST_drho');
plotCompare3D_(dJPEST_dtheta,dJpest_dtheta,'dJPEST_dtheta');
plotCompare3D_(dJPEST_dphi,dJpest_dphi,'dJPEST_dphi');

%% Shifted Metric Coordinate (SFT)

dq_drho = dq_dr;
dq_drho2 = dq_dr2;

gcon_rhorho = PESTcon_xx;
gcon_rhotheta = PESTcon_xy;
gcon_rhophi = PESTcon_xz;
gcon_thetatheta = PESTcon_yy;
gcon_thetaphi = PESTcon_yz;
gcon_phiphi = PESTcon_zz;

gcov_rhorho = PESTcov_xx;
gcov_rhotheta = PESTcov_xy;
gcov_rhophi = PESTcov_xz;
gcov_thetatheta = PESTcov_yy;
gcov_thetaphi = PESTcov_yz;
gcov_phiphi = PESTcov_zz;

vars = ["rho","theta","phi"];
metric_names = ["rhorho","rhotheta","rhophi","thetatheta","thetaphi","phiphi"];
direct_names = ["xx","xy","xz","yy","yz","zz"];
direct_vars = ["px","py","pz"];
for n=1:numel(metric_names)
    for k=1:3
        eval(['dgcon_',char(metric_names(n)),'_d',char(vars(k)),' = dPESTcon_',char(direct_names(n)),'_',char(direct_vars(k)),';']);
        eval(['dgcov_',char(metric_names(n)),'_d',char(vars(k)),' = dPESTcov_',char(direct_names(n)),'_',char(direct_vars(k)),';']);
    end
end

gconSFT=reshape({Drho.^(-2).*gcon_rhorho;
Drho.^(-1).*gcon_rhotheta;
Drho.^(-1).*(gcon_rhophi+(-1).*gcon_rhotheta.*q);
Drho.^(-1).*gcon_rhotheta;
gcon_thetatheta;
gcon_thetaphi+(-1).*gcon_thetatheta.*q;
Drho.^(-1).*(gcon_rhophi+(-1).*gcon_rhotheta.*q);
gcon_thetaphi+(-1).*gcon_thetatheta.*q;
gcon_phiphi+(-2).*gcon_thetaphi.*q+gcon_thetatheta.*q.^2;
},3,3);


dgconSFT_dx=reshape({dgcon_rhorho_drho.*Drho.^(-1);
dgcon_rhotheta_drho;
dgcon_rhophi_drho+(-1).*dq_drho.*gcon_rhotheta+(-1).* ...
dgcon_rhotheta_drho.*q;
dgcon_rhotheta_drho;
dgcon_thetatheta_drho.*Drho;
(-1).*Drho.*((-1).*dgcon_thetaphi_drho+dq_drho.*gcon_thetatheta+ ...
dgcon_thetatheta_drho.*q);
dgcon_rhophi_drho+(-1).*dq_drho.*gcon_rhotheta+(-1).* ...
dgcon_rhotheta_drho.*q;
(-1).*Drho.*((-1).*dgcon_thetaphi_drho+dq_drho.*gcon_thetatheta+ ...
dgcon_thetatheta_drho.*q);
Drho.*(dgcon_phiphi_drho+(-2).*dq_drho.*gcon_thetaphi+2.*((-1).* ...
dgcon_thetaphi_drho+dq_drho.*gcon_thetatheta).*q+ ...
dgcon_thetatheta_drho.*q.^2);
},3,3);


dgconSFT_dy=reshape({Drho.^(-2).*(dgcon_rhorho_dtheta+dgcon_rhorho_dphi.*q);
Drho.^(-1).*(dgcon_rhotheta_dtheta+dgcon_rhotheta_dphi.*q);
Drho.^(-1).*(dgcon_rhophi_dtheta+(-1).*dq_drho.*gcon_rhorho+( ...
dgcon_rhophi_dphi+(-1).*dgcon_rhotheta_dtheta).*q+(-1).* ...
dgcon_rhotheta_dphi.*q.^2);
Drho.^(-1).*(dgcon_rhotheta_dtheta+dgcon_rhotheta_dphi.*q);
dgcon_thetatheta_dtheta+dgcon_thetatheta_dphi.*q;
dgcon_thetaphi_dtheta+(-1).*dq_drho.*gcon_rhotheta+( ...
dgcon_thetaphi_dphi+(-1).*dgcon_thetatheta_dtheta).*q+(-1).* ...
dgcon_thetatheta_dphi.*q.^2;
Drho.^(-1).*(dgcon_rhophi_dtheta+(-1).*dq_drho.*gcon_rhorho+( ...
dgcon_rhophi_dphi+(-1).*dgcon_rhotheta_dtheta).*q+(-1).* ...
dgcon_rhotheta_dphi.*q.^2);
dgcon_thetaphi_dtheta+(-1).*dq_drho.*gcon_rhotheta+( ...
dgcon_thetaphi_dphi+(-1).*dgcon_thetatheta_dtheta).*q+(-1).* ...
dgcon_thetatheta_dphi.*q.^2;
dgcon_phiphi_dtheta+(-2).*dq_drho.*gcon_rhophi+(dgcon_phiphi_dphi+ ...
(-2).*dgcon_thetaphi_dtheta+2.*dq_drho.*gcon_rhotheta).*q+((-2).* ...
dgcon_thetaphi_dphi+dgcon_thetatheta_dtheta).*q.^2+ ...
dgcon_thetatheta_dphi.*q.^3;
},3,3);


dgconSFT_dz=reshape({dgcon_rhorho_dphi.*Drho.^(-2);
dgcon_rhotheta_dphi.*Drho.^(-1);
Drho.^(-1).*(dgcon_rhophi_dphi+(-1).*dgcon_rhotheta_dphi.*q);
dgcon_rhotheta_dphi.*Drho.^(-1);
dgcon_thetatheta_dphi;
dgcon_thetaphi_dphi+(-1).*dgcon_thetatheta_dphi.*q;
Drho.^(-1).*(dgcon_rhophi_dphi+(-1).*dgcon_rhotheta_dphi.*q);
dgcon_thetaphi_dphi+(-1).*dgcon_thetatheta_dphi.*q;
dgcon_phiphi_dphi+(-2).*dgcon_thetaphi_dphi.*q+ ...
dgcon_thetatheta_dphi.*q.^2;
},3,3);


gcovSFT=reshape({Drho.^2.*gcov_rhorho;
Drho.*(gcov_rhotheta+gcov_rhophi.*q);
Drho.*gcov_rhophi;
Drho.*(gcov_rhotheta+gcov_rhophi.*q);
gcov_thetatheta+q.*(2.*gcov_thetaphi+gcov_phiphi.*q);
gcov_thetaphi+gcov_phiphi.*q;
Drho.*gcov_rhophi;
gcov_thetaphi+gcov_phiphi.*q;
gcov_phiphi;
},3,3);


dgcovSFT_dx=reshape({dgcov_rhorho_drho.*Drho.^3;
Drho.^2.*(dgcov_rhotheta_drho+dq_drho.*gcov_rhophi+ ...
dgcov_rhophi_drho.*q);
dgcov_rhophi_drho.*Drho.^2;
Drho.^2.*(dgcov_rhotheta_drho+dq_drho.*gcov_rhophi+ ...
dgcov_rhophi_drho.*q);
Drho.*(dgcov_thetatheta_drho+2.*dq_drho.*gcov_thetaphi+2.*( ...
dgcov_thetaphi_drho+dq_drho.*gcov_phiphi).*q+dgcov_phiphi_drho.* ...
q.^2);
Drho.*(dgcov_thetaphi_drho+dq_drho.*gcov_phiphi+ ...
dgcov_phiphi_drho.*q);
dgcov_rhophi_drho.*Drho.^2;
Drho.*(dgcov_thetaphi_drho+dq_drho.*gcov_phiphi+ ...
dgcov_phiphi_drho.*q);
dgcov_phiphi_drho.*Drho;
},3,3);


dgcovSFT_dy=reshape({Drho.^2.*(dgcov_rhorho_dtheta+2.*dq_drho.*gcov_rhophi+ ...
dgcov_rhorho_dphi.*q);
Drho.*(dgcov_rhotheta_dtheta+dq_drho.*gcov_thetaphi+( ...
dgcov_rhophi_dtheta+dgcov_rhotheta_dphi+dq_drho.*gcov_phiphi).*q+ ...
dgcov_rhophi_dphi.*q.^2);
Drho.*(dgcov_rhophi_dtheta+dq_drho.*gcov_phiphi+ ...
dgcov_rhophi_dphi.*q);
Drho.*(dgcov_rhotheta_dtheta+dq_drho.*gcov_thetaphi+( ...
dgcov_rhophi_dtheta+dgcov_rhotheta_dphi+dq_drho.*gcov_phiphi).*q+ ...
dgcov_rhophi_dphi.*q.^2);
dgcov_thetatheta_dtheta+(2.*dgcov_thetaphi_dtheta+ ...
dgcov_thetatheta_dphi).*q+(dgcov_phiphi_dtheta+2.* ...
dgcov_thetaphi_dphi).*q.^2+dgcov_phiphi_dphi.*q.^3;
dgcov_thetaphi_dtheta+(dgcov_phiphi_dtheta+dgcov_thetaphi_dphi).* ...
q+dgcov_phiphi_dphi.*q.^2;
Drho.*(dgcov_rhophi_dtheta+dq_drho.*gcov_phiphi+ ...
dgcov_rhophi_dphi.*q);
dgcov_thetaphi_dtheta+(dgcov_phiphi_dtheta+dgcov_thetaphi_dphi).* ...
q+dgcov_phiphi_dphi.*q.^2;
dgcov_phiphi_dtheta+dgcov_phiphi_dphi.*q;
},3,3);


dgcovSFT_dz=reshape({dgcov_rhorho_dphi.*Drho.^2;
Drho.*(dgcov_rhotheta_dphi+dgcov_rhophi_dphi.*q);
dgcov_rhophi_dphi.*Drho;
Drho.*(dgcov_rhotheta_dphi+dgcov_rhophi_dphi.*q);
dgcov_thetatheta_dphi+q.*(2.*dgcov_thetaphi_dphi+ ...
dgcov_phiphi_dphi.*q);
dgcov_thetaphi_dphi+dgcov_phiphi_dphi.*q;
dgcov_rhophi_dphi.*Drho;
dgcov_thetaphi_dphi+dgcov_phiphi_dphi.*q;
dgcov_phiphi_dphi;
},3,3);

plotMetricComponents3D_(gconSFT,gcovSFT, ...
    dgconSFT_dx,dgcovSFT_dx, ...
    dgconSFT_dy,dgcovSFT_dy, ...
    dgconSFT_dz,dgcovSFT_dz, ...
    'SFT');


%% Field Aligned Coordinate (SFA)

ghost = 2;

q_withghost = zeros(N_rho,N_theta+2*ghost,N_phi);
thetap_withghost = zeros(N_rho,N_theta+2*ghost,N_phi);

for j=1:N_theta+2*ghost
    for k=1:N_phi
        q_withghost(:,j,k) = q(:,1,1);
    end
end

for i=1:N_rho
    for k=1:N_phi
        thetap_withghost(i,:,k) = -pi+(-(ghost-0.5):1:N_theta+(ghost-0.5))/N_theta*2*pi;
    end
end

qtheta = q_withghost.*thetap_withghost;

vars = ["rho","theta","phi"];

for i=1:3
    for j=i:3
        varname = ['gcov_',char(vars(i)),char(vars(j))];
        eval([varname,' = ','[',varname,'(:,end-ghost+1:end,:),',varname,',',varname,'(:,1:ghost,:)];']);
        varname = ['gcon_',char(vars(i)),char(vars(j))];
        eval([varname,' = ','[',varname,'(:,end-ghost+1:end,:),',varname,',',varname,'(:,1:ghost,:)];']);
    end
end

for i=1:3
    for j=i:3
        for k=1:3
            varname = ['dgcov_',char(vars(i)),char(vars(j)),'_d',char(vars(k))];        
            eval([varname,' = ','[',varname,'(:,end-ghost+1:end,:),',varname,',',varname,'(:,1:ghost,:)];']);
            varname = ['dgcon_',char(vars(i)),char(vars(j)),'_d',char(vars(k))];        
            eval([varname,' = ','[',varname,'(:,end-ghost+1:end,:),',varname,',',varname,'(:,1:ghost,:)];']);
        end
    end
end

gconSFA=reshape({Drho.^(-2).*gcon_rhorho;
Drho.^(-1).*gcon_rhotheta;
Drho.^(-1).*gcon_rhophi;
Drho.^(-1).*gcon_rhotheta;
gcon_thetatheta;
gcon_thetaphi;
Drho.^(-1).*gcon_rhophi;
gcon_thetaphi;
gcon_phiphi;
},3,3);

dgconSFA_dx=reshape({dgcon_rhorho_drho.*Drho.^(-1);
dgcon_rhotheta_drho;
dgcon_rhophi_drho;
dgcon_rhotheta_drho;
dgcon_thetatheta_drho.*Drho;
dgcon_thetaphi_drho.*Drho;
dgcon_rhophi_drho;
dgcon_thetaphi_drho.*Drho;
dgcon_phiphi_drho.*Drho;
},3,3);

dgconSFA_dy=reshape({dgcon_rhorho_dtheta.*Drho.^(-2);
dgcon_rhotheta_dtheta.*Drho.^(-1);
dgcon_rhophi_dtheta.*Drho.^(-1);
dgcon_rhotheta_dtheta.*Drho.^(-1);
dgcon_thetatheta_dtheta;
dgcon_thetaphi_dtheta;
dgcon_rhophi_dtheta.*Drho.^(-1);
dgcon_thetaphi_dtheta;
dgcon_phiphi_dtheta;
},3,3);

dgconSFA_dz=reshape({dgcon_rhorho_dphi.*Drho.^(-2);
dgcon_rhotheta_dphi.*Drho.^(-1);
dgcon_rhophi_dphi.*Drho.^(-1);
dgcon_rhotheta_dphi.*Drho.^(-1);
dgcon_thetatheta_dphi;
dgcon_thetaphi_dphi;
dgcon_rhophi_dphi.*Drho.^(-1);
dgcon_thetaphi_dphi;
dgcon_phiphi_dphi;
},3,3);

gcovSFA=reshape({Drho.^2.*gcov_rhorho;
Drho.*gcov_rhotheta;
Drho.*gcov_rhophi;
Drho.*gcov_rhotheta;
gcov_thetatheta;
gcov_thetaphi;
Drho.*gcov_rhophi;
gcov_thetaphi;
gcov_phiphi;
},3,3);

dgcovSFA_dx=reshape({dgcov_rhorho_drho.*Drho.^3;
dgcov_rhotheta_drho.*Drho.^2;
dgcov_rhophi_drho.*Drho.^2;
dgcov_rhotheta_drho.*Drho.^2;
dgcov_thetatheta_drho.*Drho;
dgcov_thetaphi_drho.*Drho;
dgcov_rhophi_drho.*Drho.^2;
dgcov_thetaphi_drho.*Drho;
dgcov_phiphi_drho.*Drho;
},3,3);

dgcovSFA_dy=reshape({dgcov_rhorho_dtheta.*Drho.^2;
dgcov_rhotheta_dtheta.*Drho;
dgcov_rhophi_dtheta.*Drho;
dgcov_rhotheta_dtheta.*Drho;
dgcov_thetatheta_dtheta;
dgcov_thetaphi_dtheta;
dgcov_rhophi_dtheta.*Drho;
dgcov_thetaphi_dtheta;
dgcov_phiphi_dtheta;
},3,3);

dgcovSFA_dz=reshape({dgcov_rhorho_dphi.*Drho.^2;
dgcov_rhotheta_dphi.*Drho;
dgcov_rhophi_dphi.*Drho;
dgcov_rhotheta_dphi.*Drho;
dgcov_thetatheta_dphi;
dgcov_thetaphi_dphi;
dgcov_rhophi_dphi.*Drho;
dgcov_thetaphi_dphi;
dgcov_phiphi_dphi;
},3,3);

plotMetricComponents3D_(gconSFA,gcovSFA, ...
    dgconSFA_dx,dgcovSFA_dx, ...
    dgconSFA_dy,dgcovSFA_dy, ...
    dgconSFA_dz,dgcovSFA_dz, ...
    'SFA');


%% local function

function plotCompare3D_(direct,transform,name)
relErr = (transform-direct)./direct;
errPerPhi = squeeze(max(max(abs(relErr),[],1),[],2));
[~,phiIndex] = max(errPerPhi);

plotFields3D_({direct,transform,relErr}, ...
    {[name,' (Direct)'],[name,' (Transform)'],[name,' Relative Error']}, ...
    name,phiIndex);
end

function plotMetricComponents3D_(gcon,gcov,dgcon_dx,dgcov_dx,dgcon_dy,dgcov_dy,dgcon_dz,dgcov_dz,name)
metric_names = ["xx","xy","xz","yy","yz","zz"];
metric_i = [1,1,1,2,2,3];
metric_j = [1,2,3,2,3,3];

for n = 1:numel(metric_names)
    comp = char(metric_names(n));
    i = metric_i(n);
    j = metric_j(n);

    plotFields3D_({gcon{i,j},gcov{i,j}}, ...
        {[name,' gcon_',comp],[name,' gcov_',comp]}, ...
        [name,' metric ',comp],1);

    plotFields3D_({dgcon_dx{i,j},dgcov_dx{i,j}}, ...
        {[name,' dgcon_',comp,'_dx'],[name,' dgcov_',comp,'_dx']}, ...
        [name,' metric d',comp,' dx'],1);

    plotFields3D_({dgcon_dy{i,j},dgcov_dy{i,j}}, ...
        {[name,' dgcon_',comp,'_dy'],[name,' dgcov_',comp,'_dy']}, ...
        [name,' metric d',comp,' dy'],1);

    plotFields3D_({dgcon_dz{i,j},dgcov_dz{i,j}}, ...
        {[name,' dgcon_',comp,'_dz'],[name,' dgcov_',comp,'_dz']}, ...
        [name,' metric d',comp,' dz'],1);
end
end

function plotTensorComponents3D_(tensor,name)
metric_names = ["xx","xy","xz","yx","yy","yz","zx","zy","zz"];
metric_i = [1,1,1,2,2,2,3,3,3];
metric_j = [1,2,3,1,2,3,1,2,3];

for n = 1:numel(metric_names)
    comp = char(metric_names(n));
    i = metric_i(n);
    j = metric_j(n);
    field = tensor{i,j};
    plotFields3D_({field}, {[name,' ',comp]}, [name,' ',comp],1);
end
end

function plotFields3D_(fields,field_titles,name,phiIndex)
N_phi = size(fields{1},3);
n_fields = numel(fields);
slider_max = max(N_phi,2);
slider_step = [1/(slider_max-1),min(1,5/(slider_max-1))];
if n_fields <= 3
    n_rows = 1;
    n_cols = n_fields;
else
    n_cols = ceil(sqrt(n_fields));
    n_rows = ceil(n_fields/n_cols);
end

fig = figure('Name',name);
plot_panel = uipanel('Parent',fig,'Position',[0,0.12,1,0.88],'BorderType','none');
phi_text = uicontrol('Parent',fig,'Style','text','Units','normalized', ...
    'Position',[0.42,0.075,0.16,0.03]);
phi_slider = uicontrol('Parent',fig,'Style','slider','Units','normalized', ...
    'Position',[0.18,0.03,0.64,0.04],'Min',1,'Max',slider_max, ...
    'Value',phiIndex,'SliderStep',slider_step,'Callback',@updatePhi_);

axis_handles = gobjects(1,n_fields);
mesh_handles = gobjects(1,n_fields);
for i=1:n_fields
    axis_handles(i) = subplot(n_rows,n_cols,i,'Parent',plot_panel);
    mesh_handles(i) = mesh(axis_handles(i),fields{i}(:,:,phiIndex));
end
updatePhi_(phi_slider,[]);

    function updatePhi_(~,~)
    phiIndex = round(get(phi_slider,'Value'));
    phiIndex = max(1,min(N_phi,phiIndex));
    set(phi_slider,'Value',phiIndex);
    set(phi_text,'String',['phi index = ',num2str(phiIndex),' / ',num2str(N_phi)]);
    for j=1:n_fields
        set(mesh_handles(j),'ZData',fields{j}(:,:,phiIndex),'CData',fields{j}(:,:,phiIndex));
        title(axis_handles(j),[field_titles{j},', phi=',num2str(phiIndex)]);
    end
    drawnow limitrate;
    end
end
