%%

N_rho = size(rho,1);
N_theta = size(rho,2);
Drho = rho(end,1) - rho(1,1);
I1 = ones(N_rho,N_theta);

%% Bspline Setting

order = uint64(5);

isperiodic_1d = false;
isperiodic_2d = [false,true]';
range_1d = {[refined_rho(1,1),refined_rho(end,1)]};
range_2d = {[refined_rho(1,1),refined_rho(end,1)];[refined_theta(1,1),refined_theta(1,1)+2*pi]};

coor_interp_1d = rho(:,1);
coor_interp_2d = [rho(:),theta_desc(:)];

interp_1d_ = @(f, drho) bspline(order,isperiodic_1d,range_1d,f',coor_interp_1d,uint64(drho));
interp_2d_ = @(f, drho, dtheta) reshape(bspline(order,isperiodic_2d,range_2d,f,coor_interp_2d,uint64([drho;dtheta])),N_rho,[]);

interp_2d_d1_ = @(f) deal(interp_2d_(f,0,0),interp_2d_(f,1,0),interp_2d_(f,0,1));
interp_2d_d2_ = @(f) deal(interp_2d_(f,0,0),interp_2d_(f,1,0),interp_2d_(f,0,1),interp_2d_(f,2,0),interp_2d_(f,1,1),interp_2d_(f,0,2));

%% Interpolate q,gcov

dq_dr = -diota_dr./iota.^2;
dq_dr2 = -diota_dr2./iota.^2 + 2*diota_dr.^2./iota.^3;

vars = ["r","t","z"];
for i=1:3
    for j=i:3
        varname = ['gcov_',char(vars(i)),char(vars(j))];
        eval(['d',varname,'_dr = interp_2d_(refined_',varname,',1,0);'])
        eval(['d',varname,'_dt = interp_2d_(refined_',varname,',0,1);'])

        eval(['d',varname,'_dz = zeros(N_rho,N_theta);'])
        varname = ['gcon_',char(vars(i)),char(vars(j))];
        eval(['d',varname,'_dz = zeros(N_rho,N_theta);'])
    end
end

%% 2d variable

dB_dz = zeros(N_rho,N_theta);
dB_drdz = zeros(N_rho,N_theta);
dB_dtdz = zeros(N_rho,N_theta);
dB_dz2 = zeros(N_rho,N_theta);

dR_dz = zeros(N_rho,N_theta);
dR_drdz = zeros(N_rho,N_theta);
dR_dtdz = zeros(N_rho,N_theta);
dR_dz2 = zeros(N_rho,N_theta);

dZ_dz = zeros(N_rho,N_theta);
dZ_drdz = zeros(N_rho,N_theta);
dZ_dtdz = zeros(N_rho,N_theta);
dZ_dz2 = zeros(N_rho,N_theta);

dlambda_dz = zeros(N_rho,N_theta);
dlambda_drdz = zeros(N_rho,N_theta);
dlambda_dtdz = zeros(N_rho,N_theta);
dlambda_dz2 = zeros(N_rho,N_theta);

dR_drho=dR_dr+(-1).*dlambda_dr.*(I1+dlambda_dt).^(-1).*dR_dt;
dR_dtheta=(I1+dlambda_dt).^(-1).*dR_dt;
dR_dphi=(-1).*(I1+dlambda_dt).^(-1).*dlambda_dz.*dR_dt+dR_dz;

dZ_drho=dZ_dr+(-1).*dlambda_dr.*(I1+dlambda_dt).^(-1).*dZ_dt;
dZ_dtheta=(I1+dlambda_dt).^(-1).*dZ_dt;
dZ_dphi=(-1).*(I1+dlambda_dt).^(-1).*dlambda_dz.*dZ_dt+dZ_dz;

dB_drho=dB_dr+(-1).*dB_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1);

dB_dtheta=dB_dt.*(I1+dlambda_dt).^(-1);

dB_dphi=dB_dz+(-1).*dB_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz;

dB_drho2=(I1+dlambda_dt).^(-3).*(dB_dt2.*dlambda_dr.^2.*(I1+dlambda_dt)+(I1+ ...
dlambda_dt).^2.*((-2).*dB_drdt.*dlambda_dr+dB_dr2.*(I1+dlambda_dt)) ...
+(-1).*dB_dt.*((I1+dlambda_dt).*((-2).*dlambda_dr.*dlambda_drdt+ ...
dlambda_dr2.*(I1+dlambda_dt))+dlambda_dr.^2.*dlambda_dt2));

dB_dtheta2=(I1+dlambda_dt).^(-3).*(dB_dt2.*(I1+dlambda_dt)+(-1).*dB_dt.* ...
dlambda_dt2);

dB_dphi2=dB_dz2+(I1+dlambda_dt).^(-3).*dlambda_dz.*((-2).*dB_dtdz.*(I1+ ...
dlambda_dt).^2+dB_dt2.*(I1+dlambda_dt).*dlambda_dz+dB_dt.*(2.*(I1+ ...
dlambda_dt).*dlambda_dtdz+(-1).*dlambda_dt2.*dlambda_dz))+(-1).* ...
dB_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz2;

dB_drhodtheta=(I1+dlambda_dt).^(-3).*((-1).*dB_dt2.*dlambda_dr.*(I1+dlambda_dt)+ ...
dB_drdt.*(I1+dlambda_dt).^2+dB_dt.*((-1).*dlambda_drdt.*(I1+ ...
dlambda_dt)+dlambda_dr.*dlambda_dt2));

dB_drhodphi=dB_drdz+(-1).*dB_dtdz.*dlambda_dr.*(I1+dlambda_dt).^(-1)+(-1).* ...
dB_dt.*dlambda_drdz.*(I1+dlambda_dt).^(-1)+dB_dt.*dlambda_dr.*(I1+ ...
dlambda_dt).^(-2).*dlambda_dtdz+(I1+dlambda_dt).^(-3).*(dB_dt2.* ...
dlambda_dr.*(I1+dlambda_dt)+(-1).*dB_drdt.*(I1+dlambda_dt).^2+ ...
dB_dt.*(dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.* ...
dlambda_dt2)).*dlambda_dz;

dB_dthetadphi=(I1+dlambda_dt).^(-3).*(dB_dtdz.*(I1+dlambda_dt).^2+(-1).*dB_dt2.*( ...
I1+dlambda_dt).*dlambda_dz+(-1).*dB_dt.*((I1+dlambda_dt).* ...
dlambda_dtdz+(-1).*dlambda_dt2.*dlambda_dz));

%% PEST Metric

gconPEST=reshape({gcon_rr;
dlambda_dr.*gcon_rr+(I1+dlambda_dt).*gcon_rt+dlambda_dz.*gcon_rz;
gcon_rz;
dlambda_dr.*gcon_rr+(I1+dlambda_dt).*gcon_rt+dlambda_dz.*gcon_rz;
dlambda_dr.^2.*gcon_rr+2.*dlambda_dr.*gcon_rt+2.*dlambda_dr.* ...
dlambda_dt.*gcon_rt+2.*dlambda_dr.*dlambda_dz.*gcon_rz+(I1+ ...
dlambda_dt).^2.*gcon_tt+2.*(I1+dlambda_dt).*dlambda_dz.*gcon_tz+ ...
dlambda_dz.^2.*gcon_zz;
dlambda_dr.*gcon_rz+(I1+dlambda_dt).*gcon_tz+dlambda_dz.*gcon_zz;
gcon_rz;
dlambda_dr.*gcon_rz+(I1+dlambda_dt).*gcon_tz+dlambda_dz.*gcon_zz;
gcon_zz;
},3,3);


dgconPEST_drho=reshape({dgcon_rr_dr+(-1).*dgcon_rr_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1);
dgcon_rr_dr.*dlambda_dr+dgcon_rt_dr.*(I1+dlambda_dt)+dgcon_rz_dr.* ...
dlambda_dz+dlambda_dr2.*gcon_rr+dlambda_drdt.*gcon_rt+ ...
dlambda_drdz.*gcon_rz+(-1).*dlambda_dr.*(I1+dlambda_dt).^(-1).*( ...
dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+dlambda_dt)+dgcon_rz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rr+dlambda_dt2.*gcon_rt+ ...
dlambda_dtdz.*gcon_rz);
dgcon_rz_dr+(-1).*dgcon_rz_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1);
dgcon_rr_dr.*dlambda_dr+dgcon_rt_dr.*(I1+dlambda_dt)+dgcon_rz_dr.* ...
dlambda_dz+dlambda_dr2.*gcon_rr+dlambda_drdt.*gcon_rt+ ...
dlambda_drdz.*gcon_rz+(-1).*dlambda_dr.*(I1+dlambda_dt).^(-1).*( ...
dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+dlambda_dt)+dgcon_rz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rr+dlambda_dt2.*gcon_rt+ ...
dlambda_dtdz.*gcon_rz);
2.*dgcon_rt_dr.*dlambda_dr+dgcon_rr_dr.*dlambda_dr.^2+2.* ...
dgcon_rt_dr.*dlambda_dr.*dlambda_dt+dgcon_tt_dr.*(I1+dlambda_dt) ...
.^2+2.*dgcon_rz_dr.*dlambda_dr.*dlambda_dz+2.*dgcon_tz_dr.*(I1+ ...
dlambda_dt).*dlambda_dz+dgcon_zz_dr.*dlambda_dz.^2+2.*dlambda_dr.* ...
dlambda_dr2.*gcon_rr+2.*dlambda_dr2.*gcon_rt+2.*dlambda_dr.* ...
dlambda_drdt.*gcon_rt+2.*dlambda_dr2.*dlambda_dt.*gcon_rt+2.* ...
dlambda_dr.*dlambda_drdz.*gcon_rz+2.*dlambda_dr2.*dlambda_dz.* ...
gcon_rz+2.*dlambda_drdt.*(I1+dlambda_dt).*gcon_tt+2.*dlambda_drdz.* ...
(I1+dlambda_dt).*gcon_tz+2.*dlambda_drdt.*dlambda_dz.*gcon_tz+2.* ...
dlambda_drdz.*dlambda_dz.*gcon_zz+(-1).*dlambda_dr.*(I1+dlambda_dt) ...
.^(-1).*(2.*dgcon_rt_dt.*dlambda_dr+dgcon_rr_dt.*dlambda_dr.^2+2.* ...
dgcon_rt_dt.*dlambda_dr.*dlambda_dt+dgcon_tt_dt.*(I1+dlambda_dt) ...
.^2+dgcon_zz_dt.*dlambda_dz.^2+2.*dlambda_dr.*dlambda_drdt.* ...
gcon_rr+2.*dlambda_drdt.*gcon_rt+2.*dlambda_drdt.*dlambda_dt.* ...
gcon_rt+2.*dlambda_dr.*dlambda_dt2.*gcon_rt+2.*dlambda_dr.* ...
dlambda_dtdz.*gcon_rz+2.*dlambda_dt2.*gcon_tt+2.*dlambda_dt.* ...
dlambda_dt2.*gcon_tt+2.*dlambda_dtdz.*gcon_tz+2.*dlambda_dt.* ...
dlambda_dtdz.*gcon_tz+2.*dlambda_dz.*(dgcon_rz_dt.*dlambda_dr+ ...
dgcon_tz_dt.*(I1+dlambda_dt)+dlambda_drdt.*gcon_rz+dlambda_dt2.* ...
gcon_tz+dlambda_dtdz.*gcon_zz));
dgcon_rz_dr.*dlambda_dr+dgcon_tz_dr.*(I1+dlambda_dt)+dgcon_zz_dr.* ...
dlambda_dz+dlambda_dr2.*gcon_rz+dlambda_drdt.*gcon_tz+ ...
dlambda_drdz.*gcon_zz+(-1).*dlambda_dr.*(I1+dlambda_dt).^(-1).*( ...
dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dgcon_zz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rz+dlambda_dt2.*gcon_tz+ ...
dlambda_dtdz.*gcon_zz);
dgcon_rz_dr+(-1).*dgcon_rz_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1);
dgcon_rz_dr.*dlambda_dr+dgcon_tz_dr.*(I1+dlambda_dt)+dgcon_zz_dr.* ...
dlambda_dz+dlambda_dr2.*gcon_rz+dlambda_drdt.*gcon_tz+ ...
dlambda_drdz.*gcon_zz+(-1).*dlambda_dr.*(I1+dlambda_dt).^(-1).*( ...
dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dgcon_zz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rz+dlambda_dt2.*gcon_tz+ ...
dlambda_dtdz.*gcon_zz);
dgcon_zz_dr+(-1).*dgcon_zz_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1);
},3,3);


dgconPEST_dtheta=reshape({dgcon_rr_dt.*(I1+dlambda_dt).^(-1);
(I1+dlambda_dt).^(-1).*(dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+ ...
dlambda_dt)+dgcon_rz_dt.*dlambda_dz+dlambda_drdt.*gcon_rr+ ...
dlambda_dt2.*gcon_rt+dlambda_dtdz.*gcon_rz);
dgcon_rz_dt.*(I1+dlambda_dt).^(-1);
(I1+dlambda_dt).^(-1).*(dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+ ...
dlambda_dt)+dgcon_rz_dt.*dlambda_dz+dlambda_drdt.*gcon_rr+ ...
dlambda_dt2.*gcon_rt+dlambda_dtdz.*gcon_rz);
(I1+dlambda_dt).^(-1).*(2.*dgcon_rt_dt.*dlambda_dr+dgcon_rr_dt.* ...
dlambda_dr.^2+2.*dgcon_rt_dt.*dlambda_dr.*dlambda_dt+dgcon_tt_dt.* ...
(I1+dlambda_dt).^2+dgcon_zz_dt.*dlambda_dz.^2+2.*dlambda_dr.* ...
dlambda_drdt.*gcon_rr+2.*dlambda_drdt.*gcon_rt+2.*dlambda_drdt.* ...
dlambda_dt.*gcon_rt+2.*dlambda_dr.*dlambda_dt2.*gcon_rt+2.* ...
dlambda_dr.*dlambda_dtdz.*gcon_rz+2.*dlambda_dt2.*gcon_tt+2.* ...
dlambda_dt.*dlambda_dt2.*gcon_tt+2.*dlambda_dtdz.*gcon_tz+2.* ...
dlambda_dt.*dlambda_dtdz.*gcon_tz+2.*dlambda_dz.*(dgcon_rz_dt.* ...
dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dlambda_drdt.*gcon_rz+ ...
dlambda_dt2.*gcon_tz+dlambda_dtdz.*gcon_zz));
(I1+dlambda_dt).^(-1).*(dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+ ...
dlambda_dt)+dgcon_zz_dt.*dlambda_dz+dlambda_drdt.*gcon_rz+ ...
dlambda_dt2.*gcon_tz+dlambda_dtdz.*gcon_zz);
dgcon_rz_dt.*(I1+dlambda_dt).^(-1);
(I1+dlambda_dt).^(-1).*(dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+ ...
dlambda_dt)+dgcon_zz_dt.*dlambda_dz+dlambda_drdt.*gcon_rz+ ...
dlambda_dt2.*gcon_tz+dlambda_dtdz.*gcon_zz);
dgcon_zz_dt.*(I1+dlambda_dt).^(-1);
},3,3);


dgconPEST_dphi=reshape({dgcon_rr_dz+(-1).*dgcon_rr_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz;
dgcon_rr_dz.*dlambda_dr+dgcon_rt_dz.*(I1+dlambda_dt)+dgcon_rz_dz.* ...
dlambda_dz+dlambda_drdz.*gcon_rr+dlambda_dtdz.*gcon_rt+ ...
dlambda_dz2.*gcon_rz+(-1).*(I1+dlambda_dt).^(-1).*dlambda_dz.*( ...
dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+dlambda_dt)+dgcon_rz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rr+dlambda_dt2.*gcon_rt+ ...
dlambda_dtdz.*gcon_rz);
dgcon_rz_dz+(-1).*dgcon_rz_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz;
dgcon_rr_dz.*dlambda_dr+dgcon_rt_dz.*(I1+dlambda_dt)+dgcon_rz_dz.* ...
dlambda_dz+dlambda_drdz.*gcon_rr+dlambda_dtdz.*gcon_rt+ ...
dlambda_dz2.*gcon_rz+(-1).*(I1+dlambda_dt).^(-1).*dlambda_dz.*( ...
dgcon_rr_dt.*dlambda_dr+dgcon_rt_dt.*(I1+dlambda_dt)+dgcon_rz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rr+dlambda_dt2.*gcon_rt+ ...
dlambda_dtdz.*gcon_rz);
2.*dgcon_rt_dz.*dlambda_dr+dgcon_rr_dz.*dlambda_dr.^2+2.* ...
dgcon_rt_dz.*dlambda_dr.*dlambda_dt+dgcon_tt_dz.*(I1+dlambda_dt) ...
.^2+2.*dgcon_rz_dz.*dlambda_dr.*dlambda_dz+2.*dgcon_tz_dz.*(I1+ ...
dlambda_dt).*dlambda_dz+dgcon_zz_dz.*dlambda_dz.^2+2.*dlambda_dr.* ...
dlambda_drdz.*gcon_rr+2.*dlambda_drdz.*gcon_rt+2.*dlambda_drdz.* ...
dlambda_dt.*gcon_rt+2.*dlambda_dr.*dlambda_dtdz.*gcon_rt+2.* ...
dlambda_drdz.*dlambda_dz.*gcon_rz+2.*dlambda_dr.*dlambda_dz2.* ...
gcon_rz+2.*(I1+dlambda_dt).*dlambda_dtdz.*gcon_tt+2.*dlambda_dtdz.* ...
dlambda_dz.*gcon_tz+2.*(I1+dlambda_dt).*dlambda_dz2.*gcon_tz+2.* ...
dlambda_dz.*dlambda_dz2.*gcon_zz+(-1).*(I1+dlambda_dt).^(-1).* ...
dlambda_dz.*(2.*dgcon_rt_dt.*dlambda_dr+dgcon_rr_dt.* ...
dlambda_dr.^2+2.*dgcon_rt_dt.*dlambda_dr.*dlambda_dt+dgcon_tt_dt.* ...
(I1+dlambda_dt).^2+dgcon_zz_dt.*dlambda_dz.^2+2.*dlambda_dr.* ...
dlambda_drdt.*gcon_rr+2.*dlambda_drdt.*gcon_rt+2.*dlambda_drdt.* ...
dlambda_dt.*gcon_rt+2.*dlambda_dr.*dlambda_dt2.*gcon_rt+2.* ...
dlambda_dr.*dlambda_dtdz.*gcon_rz+2.*dlambda_dt2.*gcon_tt+2.* ...
dlambda_dt.*dlambda_dt2.*gcon_tt+2.*dlambda_dtdz.*gcon_tz+2.* ...
dlambda_dt.*dlambda_dtdz.*gcon_tz+2.*dlambda_dz.*(dgcon_rz_dt.* ...
dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dlambda_drdt.*gcon_rz+ ...
dlambda_dt2.*gcon_tz+dlambda_dtdz.*gcon_zz));
dgcon_rz_dz.*dlambda_dr+dgcon_tz_dz.*(I1+dlambda_dt)+dgcon_zz_dz.* ...
dlambda_dz+dlambda_drdz.*gcon_rz+dlambda_dtdz.*gcon_tz+ ...
dlambda_dz2.*gcon_zz+(-1).*(I1+dlambda_dt).^(-1).*dlambda_dz.*( ...
dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dgcon_zz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rz+dlambda_dt2.*gcon_tz+ ...
dlambda_dtdz.*gcon_zz);
dgcon_rz_dz+(-1).*dgcon_rz_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz;
dgcon_rz_dz.*dlambda_dr+dgcon_tz_dz.*(I1+dlambda_dt)+dgcon_zz_dz.* ...
dlambda_dz+dlambda_drdz.*gcon_rz+dlambda_dtdz.*gcon_tz+ ...
dlambda_dz2.*gcon_zz+(-1).*(I1+dlambda_dt).^(-1).*dlambda_dz.*( ...
dgcon_rz_dt.*dlambda_dr+dgcon_tz_dt.*(I1+dlambda_dt)+dgcon_zz_dt.* ...
dlambda_dz+dlambda_drdt.*gcon_rz+dlambda_dt2.*gcon_tz+ ...
dlambda_dtdz.*gcon_zz);
dgcon_zz_dz+(-1).*dgcon_zz_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz;
},3,3);


gcovPEST=reshape({gcov_rr+dlambda_dr.*(I1+dlambda_dt).^(-2).*((-2).*(I1+dlambda_dt).* ...
gcov_rt+dlambda_dr.*gcov_tt);
(I1+dlambda_dt).^(-2).*((I1+dlambda_dt).*gcov_rt+(-1).*dlambda_dr.* ...
gcov_tt);
gcov_rz+(-1).*(I1+dlambda_dt).^(-2).*((I1+dlambda_dt).*dlambda_dz.* ...
gcov_rt+dlambda_dr.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz));
(I1+dlambda_dt).^(-2).*((I1+dlambda_dt).*gcov_rt+(-1).*dlambda_dr.* ...
gcov_tt);
(I1+dlambda_dt).^(-2).*gcov_tt;
(I1+dlambda_dt).^(-2).*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz);
gcov_rz+(-1).*(I1+dlambda_dt).^(-2).*((I1+dlambda_dt).*dlambda_dz.* ...
gcov_rt+dlambda_dr.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz));
(I1+dlambda_dt).^(-2).*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz);
(I1+dlambda_dt).^(-2).*dlambda_dz.*(dlambda_dz.*gcov_tt+(-2).*(I1+ ...
dlambda_dt).*gcov_tz)+gcov_zz;
},3,3);


dgcovPEST_drho=reshape({dgcov_rr_dr+dgcov_tt_dr.*dlambda_dr.^2.*(I1+dlambda_dt).^(-2)+(-1) ...
.*dgcov_rr_dt.*dlambda_dr.*(I1+dlambda_dt).^(-1)+(-2).* ...
dgcov_rt_dr.*dlambda_dr.*(I1+dlambda_dt).^(-1)+2.*dlambda_dr.* ...
dlambda_drdt.*(I1+dlambda_dt).^(-2).*gcov_rt+(-2).*dlambda_dr2.*(I1+ ...
dlambda_dt).^(-1).*gcov_rt+(-2).*dlambda_dr.^2.*dlambda_drdt.*(I1+ ...
dlambda_dt).^(-3).*gcov_tt+2.*dlambda_dr.*dlambda_dr2.*(I1+ ...
dlambda_dt).^(-2).*gcov_tt+dlambda_dr.*(I1+dlambda_dt).^(-4).*(2.* ...
dgcov_rt_dt.*dlambda_dr.*(I1+dlambda_dt).^2+2.*(I1+dlambda_dt).*( ...
dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_rt+(-1).*dlambda_dr.*(dgcov_tt_dt.*dlambda_dr.*(I1+dlambda_dt) ...
+2.*(dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_tt));
(I1+dlambda_dt).^(-3).*((-2).*dlambda_drdt.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dr.*dlambda_dr+dgcov_rt_dr.*(I1+dlambda_dt)+dlambda_drdt.* ...
gcov_rt+(-1).*dlambda_dr2.*gcov_tt)+dlambda_dr.*(dgcov_tt_dt.* ...
dlambda_dr+(-1).*dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.*gcov_rt+ ...
dlambda_drdt.*gcov_tt+(-2).*dlambda_dr.*(I1+dlambda_dt).^(-1).* ...
dlambda_dt2.*gcov_tt));
dgcov_rz_dr+(-1).*(I1+dlambda_dt).^(-2).*(dlambda_dz.*((-1).* ...
dgcov_tt_dr.*dlambda_dr+dgcov_rt_dr.*(I1+dlambda_dt)+dlambda_drdt.* ...
gcov_rt+(-1).*dlambda_dr2.*gcov_tt)+(I1+dlambda_dt).*( ...
dlambda_drdz.*gcov_rt+dlambda_dr2.*gcov_tz)+dlambda_dr.*( ...
dgcov_tz_dr.*(I1+dlambda_dt)+(-1).*dlambda_drdz.*gcov_tt+ ...
dlambda_drdt.*gcov_tz))+2.*dlambda_drdt.*(I1+dlambda_dt).^(-3).*(( ...
I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.* ...
gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*dlambda_dr.*(I1+dlambda_dt) ...
.^(-1).*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).*dlambda_dt2.*((I1+ ...
dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.* ...
gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+dlambda_dt).^(-2).*( ...
dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+dlambda_dt).* ...
dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.*gcov_rt+ ...
dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+ ...
dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dgcov_tt_dt.* ...
dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.*gcov_tz)));
(I1+dlambda_dt).^(-3).*((-2).*dlambda_drdt.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dr.*dlambda_dr+dgcov_rt_dr.*(I1+dlambda_dt)+dlambda_drdt.* ...
gcov_rt+(-1).*dlambda_dr2.*gcov_tt)+dlambda_dr.*(dgcov_tt_dt.* ...
dlambda_dr+(-1).*dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.*gcov_rt+ ...
dlambda_drdt.*gcov_tt+(-2).*dlambda_dr.*(I1+dlambda_dt).^(-1).* ...
dlambda_dt2.*gcov_tt));
(I1+dlambda_dt).^(-4).*((-1).*dgcov_tt_dt.*dlambda_dr.*(I1+ ...
dlambda_dt)+dgcov_tt_dr.*(I1+dlambda_dt).^2+2.*((-1).* ...
dlambda_drdt.*(I1+dlambda_dt)+dlambda_dr.*dlambda_dt2).*gcov_tt);
(I1+dlambda_dt).^(-3).*((I1+dlambda_dt).*(dgcov_tz_dr.*(I1+ ...
dlambda_dt)+(-1).*dgcov_tt_dr.*dlambda_dz+(-1).*dlambda_drdz.* ...
gcov_tt+dlambda_drdt.*gcov_tz)+(-2).*dlambda_drdt.*((-1).* ...
dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+dlambda_dr.*((-1).* ...
dgcov_tz_dt.*(I1+dlambda_dt)+dlambda_dtdz.*gcov_tt+dlambda_dz.*( ...
dgcov_tt_dt+(-2).*(I1+dlambda_dt).^(-1).*dlambda_dt2.*gcov_tt)+ ...
dlambda_dt2.*gcov_tz));
dgcov_rz_dr+(-1).*(I1+dlambda_dt).^(-2).*(dlambda_dz.*((-1).* ...
dgcov_tt_dr.*dlambda_dr+dgcov_rt_dr.*(I1+dlambda_dt)+dlambda_drdt.* ...
gcov_rt+(-1).*dlambda_dr2.*gcov_tt)+(I1+dlambda_dt).*( ...
dlambda_drdz.*gcov_rt+dlambda_dr2.*gcov_tz)+dlambda_dr.*( ...
dgcov_tz_dr.*(I1+dlambda_dt)+(-1).*dlambda_drdz.*gcov_tt+ ...
dlambda_drdt.*gcov_tz))+2.*dlambda_drdt.*(I1+dlambda_dt).^(-3).*(( ...
I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.* ...
gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*dlambda_dr.*(I1+dlambda_dt) ...
.^(-1).*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).*dlambda_dt2.*((I1+ ...
dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.* ...
gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+dlambda_dt).^(-2).*( ...
dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+dlambda_dt).* ...
dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.*gcov_rt+ ...
dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+ ...
dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dgcov_tt_dt.* ...
dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.*gcov_tz)));
(I1+dlambda_dt).^(-3).*((I1+dlambda_dt).*(dgcov_tz_dr.*(I1+ ...
dlambda_dt)+(-1).*dgcov_tt_dr.*dlambda_dz+(-1).*dlambda_drdz.* ...
gcov_tt+dlambda_drdt.*gcov_tz)+(-2).*dlambda_drdt.*((-1).* ...
dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+dlambda_dr.*((-1).* ...
dgcov_tz_dt.*(I1+dlambda_dt)+dlambda_dtdz.*gcov_tt+dlambda_dz.*( ...
dgcov_tt_dt+(-2).*(I1+dlambda_dt).^(-1).*dlambda_dt2.*gcov_tt)+ ...
dlambda_dt2.*gcov_tz));
dgcov_zz_dr+(I1+dlambda_dt).^(-2).*dlambda_dz.*((-2).*dgcov_tz_dr.* ...
(I1+dlambda_dt)+dgcov_tt_dr.*dlambda_dz+dlambda_drdz.*gcov_tt+(-2) ...
.*dlambda_drdt.*gcov_tz)+dlambda_drdz.*(I1+dlambda_dt).^(-2).*( ...
dlambda_dz.*gcov_tt+(-2).*(I1+dlambda_dt).*gcov_tz)+(-2).* ...
dlambda_drdt.*(I1+dlambda_dt).^(-3).*dlambda_dz.*(dlambda_dz.* ...
gcov_tt+(-2).*(I1+dlambda_dt).*gcov_tz)+(-1).*dlambda_dr.*(I1+ ...
dlambda_dt).^(-4).*(dlambda_dz.^2.*(dgcov_tt_dt.*(I1+dlambda_dt)+( ...
-2).*dlambda_dt2.*gcov_tt)+(-2).*(I1+dlambda_dt).*dlambda_dz.*( ...
dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dlambda_dtdz.*gcov_tt+(-1).* ...
dlambda_dt2.*gcov_tz)+(I1+dlambda_dt).^2.*(dgcov_zz_dt.*(I1+ ...
dlambda_dt)+(-2).*dlambda_dtdz.*gcov_tz));
},3,3);


dgcovPEST_dtheta=reshape({(I1+dlambda_dt).^(-1).*(dgcov_rr_dt+(I1+dlambda_dt).^(-3).*((-2).* ...
dgcov_rt_dt.*dlambda_dr.*(I1+dlambda_dt).^2+(-2).*(I1+dlambda_dt).*( ...
dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_rt+dlambda_dr.*(dgcov_tt_dt.*dlambda_dr.*(I1+dlambda_dt)+2.*( ...
dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_tt)));
(I1+dlambda_dt).^(-4).*((-2).*dlambda_dt2.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dt.*dlambda_dr+dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.* ...
gcov_rt+(-1).*dlambda_drdt.*gcov_tt));
(I1+dlambda_dt).^(-1).*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*(( ...
-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+ ...
dlambda_dt).^(-2).*(dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+ ...
dlambda_dt).*dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.* ...
gcov_rt+dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz)+dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).* ...
dgcov_tt_dt.*dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.* ...
gcov_tz)));
(I1+dlambda_dt).^(-4).*((-2).*dlambda_dt2.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dt.*dlambda_dr+dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.* ...
gcov_rt+(-1).*dlambda_drdt.*gcov_tt));
(I1+dlambda_dt).^(-4).*(dgcov_tt_dt.*(I1+dlambda_dt)+(-2).* ...
dlambda_dt2.*gcov_tt);
(I1+dlambda_dt).^(-4).*((-1).*dlambda_dz.*(dgcov_tt_dt.*(I1+ ...
dlambda_dt)+(-2).*dlambda_dt2.*gcov_tt)+(I1+dlambda_dt).*( ...
dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dlambda_dtdz.*gcov_tt+(-1).* ...
dlambda_dt2.*gcov_tz));
(I1+dlambda_dt).^(-1).*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*(( ...
-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+ ...
dlambda_dt).^(-2).*(dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+ ...
dlambda_dt).*dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.* ...
gcov_rt+dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz)+dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).* ...
dgcov_tt_dt.*dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.* ...
gcov_tz)));
(I1+dlambda_dt).^(-4).*((-1).*dlambda_dz.*(dgcov_tt_dt.*(I1+ ...
dlambda_dt)+(-2).*dlambda_dt2.*gcov_tt)+(I1+dlambda_dt).*( ...
dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dlambda_dtdz.*gcov_tt+(-1).* ...
dlambda_dt2.*gcov_tz));
(I1+dlambda_dt).^(-4).*(dlambda_dz.^2.*(dgcov_tt_dt.*(I1+dlambda_dt) ...
+(-2).*dlambda_dt2.*gcov_tt)+(-2).*(I1+dlambda_dt).*dlambda_dz.*( ...
dgcov_tz_dt.*(I1+dlambda_dt)+(-1).*dlambda_dtdz.*gcov_tt+(-1).* ...
dlambda_dt2.*gcov_tz)+(I1+dlambda_dt).^2.*(dgcov_zz_dt.*(I1+ ...
dlambda_dt)+(-2).*dlambda_dtdz.*gcov_tz));
},3,3);


dgcovPEST_dphi=reshape({dgcov_rr_dz+dgcov_tt_dz.*dlambda_dr.^2.*(I1+dlambda_dt).^(-2)+(-2) ...
.*dgcov_rt_dz.*dlambda_dr.*(I1+dlambda_dt).^(-1)+(-1).* ...
dgcov_rr_dt.*(I1+dlambda_dt).^(-1).*dlambda_dz+(-2).*dlambda_drdz.* ...
(I1+dlambda_dt).^(-1).*gcov_rt+2.*dlambda_dr.*(I1+dlambda_dt).^(-2) ...
.*dlambda_dtdz.*gcov_rt+2.*dlambda_dr.*dlambda_drdz.*(I1+ ...
dlambda_dt).^(-2).*gcov_tt+(-2).*dlambda_dr.^2.*(I1+dlambda_dt).^( ...
-3).*dlambda_dtdz.*gcov_tt+(I1+dlambda_dt).^(-4).*dlambda_dz.*(2.* ...
dgcov_rt_dt.*dlambda_dr.*(I1+dlambda_dt).^2+2.*(I1+dlambda_dt).*( ...
dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_rt+(-1).*dlambda_dr.*(dgcov_tt_dt.*dlambda_dr.*(I1+dlambda_dt) ...
+2.*(dlambda_drdt.*(I1+dlambda_dt)+(-1).*dlambda_dr.*dlambda_dt2).* ...
gcov_tt));
(I1+dlambda_dt).^(-3).*((-2).*dlambda_dtdz.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dz.*dlambda_dr+dgcov_rt_dz.*(I1+dlambda_dt)+dlambda_dtdz.* ...
gcov_rt+(-1).*dlambda_drdz.*gcov_tt)+dlambda_dz.*(dgcov_tt_dt.* ...
dlambda_dr+(-1).*dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.*gcov_rt+ ...
dlambda_drdt.*gcov_tt+(-2).*dlambda_dr.*(I1+dlambda_dt).^(-1).* ...
dlambda_dt2.*gcov_tt));
dgcov_rz_dz+2.*(I1+dlambda_dt).^(-3).*dlambda_dtdz.*((I1+dlambda_dt) ...
.*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.*gcov_tt+(I1+ ...
dlambda_dt).*gcov_tz))+(-1).*(I1+dlambda_dt).^(-2).*(dgcov_rt_dz.*( ...
I1+dlambda_dt).*dlambda_dz+dlambda_dtdz.*dlambda_dz.*gcov_rt+(I1+ ...
dlambda_dt).*dlambda_dz2.*gcov_rt+dlambda_drdz.*((-1).* ...
dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+dlambda_dr.*( ...
dgcov_tz_dz.*(I1+dlambda_dt)+(-1).*dgcov_tt_dz.*dlambda_dz+(-1).* ...
dlambda_dz2.*gcov_tt+dlambda_dtdz.*gcov_tz))+(-1).*(I1+dlambda_dt) ...
.^(-1).*dlambda_dz.*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*(( ...
-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+ ...
dlambda_dt).^(-2).*(dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+ ...
dlambda_dt).*dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.* ...
gcov_rt+dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz)+dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).* ...
dgcov_tt_dt.*dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.* ...
gcov_tz)));
(I1+dlambda_dt).^(-3).*((-2).*dlambda_dtdz.*((I1+dlambda_dt).* ...
gcov_rt+(-1).*dlambda_dr.*gcov_tt)+(I1+dlambda_dt).*((-1).* ...
dgcov_tt_dz.*dlambda_dr+dgcov_rt_dz.*(I1+dlambda_dt)+dlambda_dtdz.* ...
gcov_rt+(-1).*dlambda_drdz.*gcov_tt)+dlambda_dz.*(dgcov_tt_dt.* ...
dlambda_dr+(-1).*dgcov_rt_dt.*(I1+dlambda_dt)+dlambda_dt2.*gcov_rt+ ...
dlambda_drdt.*gcov_tt+(-2).*dlambda_dr.*(I1+dlambda_dt).^(-1).* ...
dlambda_dt2.*gcov_tt));
(I1+dlambda_dt).^(-4).*(dgcov_tt_dz.*(I1+dlambda_dt).^2+(-2).*(I1+ ...
dlambda_dt).*dlambda_dtdz.*gcov_tt+(-1).*dlambda_dz.*( ...
dgcov_tt_dt.*(I1+dlambda_dt)+(-2).*dlambda_dt2.*gcov_tt));
(I1+dlambda_dt).^(-4).*(dlambda_dz.^2.*(dgcov_tt_dt.*(I1+dlambda_dt) ...
+(-2).*dlambda_dt2.*gcov_tt)+(-1).*(I1+dlambda_dt).*dlambda_dz.*( ...
dgcov_tt_dz.*(I1+dlambda_dt)+dgcov_tz_dt.*(I1+dlambda_dt)+(-3).* ...
dlambda_dtdz.*gcov_tt+(-1).*dlambda_dt2.*gcov_tz)+(I1+dlambda_dt) ...
.^2.*(dgcov_tz_dz.*(I1+dlambda_dt)+(-1).*dlambda_dz2.*gcov_tt+(-1) ...
.*dlambda_dtdz.*gcov_tz));
dgcov_rz_dz+2.*(I1+dlambda_dt).^(-3).*dlambda_dtdz.*((I1+dlambda_dt) ...
.*dlambda_dz.*gcov_rt+dlambda_dr.*((-1).*dlambda_dz.*gcov_tt+(I1+ ...
dlambda_dt).*gcov_tz))+(-1).*(I1+dlambda_dt).^(-2).*(dgcov_rt_dz.*( ...
I1+dlambda_dt).*dlambda_dz+dlambda_dtdz.*dlambda_dz.*gcov_rt+(I1+ ...
dlambda_dt).*dlambda_dz2.*gcov_rt+dlambda_drdz.*((-1).* ...
dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz)+dlambda_dr.*( ...
dgcov_tz_dz.*(I1+dlambda_dt)+(-1).*dgcov_tt_dz.*dlambda_dz+(-1).* ...
dlambda_dz2.*gcov_tt+dlambda_dtdz.*gcov_tz))+(-1).*(I1+dlambda_dt) ...
.^(-1).*dlambda_dz.*(dgcov_rz_dt+2.*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((I1+dlambda_dt).*dlambda_dz.*gcov_rt+dlambda_dr.*(( ...
-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).*gcov_tz))+(-1).*(I1+ ...
dlambda_dt).^(-2).*(dgcov_rt_dt.*(I1+dlambda_dt).*dlambda_dz+(I1+ ...
dlambda_dt).*dlambda_dtdz.*gcov_rt+dlambda_dt2.*dlambda_dz.* ...
gcov_rt+dlambda_drdt.*((-1).*dlambda_dz.*gcov_tt+(I1+dlambda_dt).* ...
gcov_tz)+dlambda_dr.*(dgcov_tz_dt.*(I1+dlambda_dt)+(-1).* ...
dgcov_tt_dt.*dlambda_dz+(-1).*dlambda_dtdz.*gcov_tt+dlambda_dt2.* ...
gcov_tz)));
(I1+dlambda_dt).^(-4).*(dlambda_dz.^2.*(dgcov_tt_dt.*(I1+dlambda_dt) ...
+(-2).*dlambda_dt2.*gcov_tt)+(-1).*(I1+dlambda_dt).*dlambda_dz.*( ...
dgcov_tt_dz.*(I1+dlambda_dt)+dgcov_tz_dt.*(I1+dlambda_dt)+(-3).* ...
dlambda_dtdz.*gcov_tt+(-1).*dlambda_dt2.*gcov_tz)+(I1+dlambda_dt) ...
.^2.*(dgcov_tz_dz.*(I1+dlambda_dt)+(-1).*dlambda_dz2.*gcov_tt+(-1) ...
.*dlambda_dtdz.*gcov_tz));
(I1+dlambda_dt).^(-4).*(dgcov_zz_dz.*(I1+dlambda_dt).^4+(-2).* ...
dgcov_tz_dz.*(I1+dlambda_dt).^3.*dlambda_dz+(-1).*dgcov_zz_dt.*(I1+ ...
dlambda_dt).^3.*dlambda_dz+dgcov_tt_dz.*(I1+dlambda_dt).^2.* ...
dlambda_dz.^2+2.*dgcov_tz_dt.*(I1+dlambda_dt).^2.*dlambda_dz.^2+( ...
-1).*dgcov_tt_dt.*(I1+dlambda_dt).*dlambda_dz.^3+(-4).*(I1+ ...
dlambda_dt).*dlambda_dtdz.*dlambda_dz.^2.*gcov_tt+2.*dlambda_dt2.* ...
dlambda_dz.^3.*gcov_tt+2.*(I1+dlambda_dt).^2.*dlambda_dz.* ...
dlambda_dz2.*gcov_tt+4.*(I1+dlambda_dt).^2.*dlambda_dtdz.* ...
dlambda_dz.*gcov_tz+(-2).*(I1+dlambda_dt).*dlambda_dt2.* ...
dlambda_dz.^2.*gcov_tz+(-2).*(I1+dlambda_dt).^3.*dlambda_dz2.* ...
gcov_tz);
},3,3);


figure;
subplot(1,3,1);
mesh(PESTcon_xx);
title('PESTconxx (DESC)');
subplot(1,3,2);
mesh(gconPEST{1,1});
title('PESTconxx (Transform)');
subplot(1,3,3);
mesh((gconPEST{1,1}-PESTcon_xx)./PESTcon_xx);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(PESTcon_xy);
title('PESTconxy (DESC)');
subplot(1,3,2);
mesh(gconPEST{1,2});
title('PESTconxy (Transform)');
subplot(1,3,3);
mesh((gconPEST{1,2}-PESTcon_xy)./PESTcon_xy);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(PESTcon_xz);
title('PESTconxz (DESC)');
subplot(1,3,2);
mesh(gconPEST{1,3});
title('PESTconxz (Transform)');
subplot(1,3,3);
mesh((gconPEST{1,3}-PESTcon_xz));
title('Relative Error');


figure;
subplot(1,3,1);
mesh(PESTcon_yy);
title('PESTconyy (DESC)');
subplot(1,3,2);
mesh(gconPEST{2,2});
title('PESTconyy (Transform)');
subplot(1,3,3);
mesh((gconPEST{2,2}-PESTcon_yy)./PESTcon_yy);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(PESTcon_yz);
title('PESTconyz (DESC)');
subplot(1,3,2);
mesh(gconPEST{2,3});
title('PESTconyz (Transform)');
subplot(1,3,3);
mesh((gconPEST{2,3}-PESTcon_yz));
title('Relative Error');


figure;
subplot(1,3,1);
mesh(PESTcon_zz);
title('PESTconzz (DESC)');
subplot(1,3,2);
mesh(gconPEST{3,3});
title('PESTconzz (Transform)');
subplot(1,3,3);
mesh((gconPEST{3,3}-PESTcon_zz)./PESTcon_zz);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(PESTcov_xx);
title('PESTcovxx (DESC)');
subplot(1,3,2);
mesh(gcovPEST{1,1});
title('PESTcovxx (Transform)');
subplot(1,3,3);
mesh((gcovPEST{1,1}-PESTcov_xx)./PESTcov_xx);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(PESTcov_xy);
title('PESTcovxy (DESC)');
subplot(1,3,2);
mesh(gcovPEST{1,2});
title('PESTcovxy (Transform)');
subplot(1,3,3);
mesh((gcovPEST{1,2}-PESTcov_xy)./PESTcov_xy);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(PESTcov_xz);
title('PESTcovxz (DESC)');
subplot(1,3,2);
mesh(gcovPEST{1,3});
title('PESTcovxz (Transform)');
subplot(1,3,3);
mesh((gcovPEST{1,3}-PESTcov_xz));
title('Relative Error');


figure;
subplot(1,3,1);
mesh(PESTcov_yy);
title('PESTcovyy (DESC)');
subplot(1,3,2);
mesh(gcovPEST{2,2});
title('PESTcovyy (Transform)');
subplot(1,3,3);
mesh((gcovPEST{2,2}-PESTcov_yy)./PESTcov_yy);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(PESTcov_yz);
title('PESTcovyz (DESC)');
subplot(1,3,2);
mesh(gcovPEST{2,3});
title('PESTcovyz (Transform)');
subplot(1,3,3);
mesh((gcovPEST{2,3}-PESTcov_yz));
title('Relative Error');


figure;
subplot(1,3,1);
mesh(PESTcov_zz);
title('PESTcovzz (DESC)');
subplot(1,3,2);
mesh(gcovPEST{3,3});
title('PESTcovzz (Transform)');
subplot(1,3,3);
mesh((gcovPEST{3,3}-PESTcov_zz)./PESTcov_zz);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(dPESTcon_xx_py);
title('dPESTconxx/dy (DESC)');
subplot(1,3,2);
mesh(dgconPEST_dtheta{1,1});
title('dPESTconxx/dy (Transform)');
subplot(1,3,3);
mesh((dgconPEST_dtheta{1,1}-dPESTcon_xx_py)./dPESTcon_xx_py);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(dPESTcon_xy_py);
title('dPESTconxy/dy (DESC)');
subplot(1,3,2);
mesh(dgconPEST_dtheta{1,2});
title('dPESTconxy/dy (Transform)');
subplot(1,3,3);
mesh((dgconPEST_dtheta{1,2}-dPESTcon_xy_py)./dPESTcon_xy_py);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(dPESTcon_xz_py);
title('dPESTconxz/dy (DESC)');
subplot(1,3,2);
mesh(dgconPEST_dtheta{1,3});
title('dPESTconxz/dy (Transform)');
subplot(1,3,3);
mesh((dgconPEST_dtheta{1,3}-dPESTcon_xz_py));
title('Relative Error');


figure;
subplot(1,3,1);
mesh(dPESTcov_xx_py);
title('dPESTcovxx/dy (DESC)');
subplot(1,3,2);
mesh(dgcovPEST_dtheta{1,1});
title('dPESTcovxx/dy (Transform)');
subplot(1,3,3);
mesh((dgcovPEST_dtheta{1,1}-dPESTcov_xx_py)./dPESTcov_xx_py);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(dPESTcov_yy_px);
title('dPESTcovyy/dx (DESC)');
subplot(1,3,2);
mesh(dgcovPEST_drho{2,2});
title('dPESTcovyy/dx (Transform)');
subplot(1,3,3);
mesh((dgcovPEST_drho{2,2}-dPESTcov_yy_px)./dPESTcov_yy_px);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(dPESTcov_zz_py);
title('dPESTcovzz/dy (DESC)');
subplot(1,3,2);
mesh(dgcovPEST_dtheta{3,3});
title('dPESTcovzz/dy (Transform)');
subplot(1,3,3);
mesh((dgcovPEST_dtheta{3,3}-dPESTcov_zz_py)./dPESTcov_zz_py);
title('Relative Error');


%% PEST Jacobian

Jpest=((I1+dlambda_dt).^(-2).*((-1).*gcov_rz.^2.*gcov_tt+2.*gcov_rt.* ...
gcov_rz.*gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).* ...
gcov_tz.^2+gcov_tt.*gcov_zz))).^(1/2);


dJpest_drho=(1/2).*((I1+dlambda_dt).^(-2).*((-1).*gcov_rz.^2.*gcov_tt+2.* ...
gcov_rt.*gcov_rz.*gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1) ...
.*gcov_tz.^2+gcov_tt.*gcov_zz))).^(-1/2).*((I1+dlambda_dt).^(-2).*( ...
(-1).*dgcov_zz_dr.*gcov_rt.^2+2.*dgcov_tz_dr.*gcov_rt.*gcov_rz+( ...
-1).*dgcov_tt_dr.*gcov_rz.^2+(-2).*dgcov_rz_dr.*gcov_rz.*gcov_tt+ ...
2.*dgcov_rz_dr.*gcov_rt.*gcov_tz+2.*dgcov_rt_dr.*gcov_rz.*gcov_tz+ ...
(-2).*dgcov_rt_dr.*gcov_rt.*gcov_zz+gcov_rr.*(dgcov_zz_dr.* ...
gcov_tt+(-2).*dgcov_tz_dr.*gcov_tz+dgcov_tt_dr.*gcov_zz)+ ...
dgcov_rr_dr.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))+(-2).* ...
dlambda_drdt.*(I1+dlambda_dt).^(-3).*((-1).*gcov_rz.^2.*gcov_tt+2.* ...
gcov_rt.*gcov_rz.*gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1) ...
.*gcov_tz.^2+gcov_tt.*gcov_zz)))+(-1/2).*dlambda_dr.*(I1+ ...
dlambda_dt).^(-1).*((I1+dlambda_dt).^(-2).*((-1).*gcov_rz.^2.* ...
gcov_tt+2.*gcov_rt.*gcov_rz.*gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+ ...
gcov_rr.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))).^(-1/2).*((I1+ ...
dlambda_dt).^(-2).*((-1).*dgcov_zz_dt.*gcov_rt.^2+2.*dgcov_tz_dt.* ...
gcov_rt.*gcov_rz+(-1).*dgcov_tt_dt.*gcov_rz.^2+(-2).*dgcov_rz_dt.* ...
gcov_rz.*gcov_tt+2.*dgcov_rz_dt.*gcov_rt.*gcov_tz+2.*dgcov_rt_dt.* ...
gcov_rz.*gcov_tz+(-2).*dgcov_rt_dt.*gcov_rt.*gcov_zz+gcov_rr.*( ...
dgcov_zz_dt.*gcov_tt+(-2).*dgcov_tz_dt.*gcov_tz+dgcov_tt_dt.* ...
gcov_zz)+dgcov_rr_dt.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))+(-2).*( ...
I1+dlambda_dt).^(-3).*dlambda_dt2.*((-1).*gcov_rz.^2.*gcov_tt+2.* ...
gcov_rt.*gcov_rz.*gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1) ...
.*gcov_tz.^2+gcov_tt.*gcov_zz)));


dJpest_dtheta=(1/2).*(I1+dlambda_dt).^(-1).*((I1+dlambda_dt).^(-2).*((-1).* ...
gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.*gcov_tz+(-1).* ...
gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))) ...
.^(-1/2).*((I1+dlambda_dt).^(-2).*((-1).*dgcov_zz_dt.*gcov_rt.^2+ ...
2.*dgcov_tz_dt.*gcov_rt.*gcov_rz+(-1).*dgcov_tt_dt.*gcov_rz.^2+( ...
-2).*dgcov_rz_dt.*gcov_rz.*gcov_tt+2.*dgcov_rz_dt.*gcov_rt.* ...
gcov_tz+2.*dgcov_rt_dt.*gcov_rz.*gcov_tz+(-2).*dgcov_rt_dt.* ...
gcov_rt.*gcov_zz+gcov_rr.*(dgcov_zz_dt.*gcov_tt+(-2).* ...
dgcov_tz_dt.*gcov_tz+dgcov_tt_dt.*gcov_zz)+dgcov_rr_dt.*((-1).* ...
gcov_tz.^2+gcov_tt.*gcov_zz))+(-2).*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((-1).*gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.* ...
gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+ ...
gcov_tt.*gcov_zz)));


dJpest_dphi=(-1/2).*(I1+dlambda_dt).^(-1).*dlambda_dz.*((I1+dlambda_dt).^(-2).*( ...
(-1).*gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.*gcov_tz+(-1).* ...
gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))) ...
.^(-1/2).*((I1+dlambda_dt).^(-2).*((-1).*dgcov_zz_dt.*gcov_rt.^2+ ...
2.*dgcov_tz_dt.*gcov_rt.*gcov_rz+(-1).*dgcov_tt_dt.*gcov_rz.^2+( ...
-2).*dgcov_rz_dt.*gcov_rz.*gcov_tt+2.*dgcov_rz_dt.*gcov_rt.* ...
gcov_tz+2.*dgcov_rt_dt.*gcov_rz.*gcov_tz+(-2).*dgcov_rt_dt.* ...
gcov_rt.*gcov_zz+gcov_rr.*(dgcov_zz_dt.*gcov_tt+(-2).* ...
dgcov_tz_dt.*gcov_tz+dgcov_tt_dt.*gcov_zz)+dgcov_rr_dt.*((-1).* ...
gcov_tz.^2+gcov_tt.*gcov_zz))+(-2).*(I1+dlambda_dt).^(-3).* ...
dlambda_dt2.*((-1).*gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.* ...
gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+ ...
gcov_tt.*gcov_zz)))+(1/2).*((I1+dlambda_dt).^(-2).*((-1).* ...
gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.*gcov_tz+(-1).* ...
gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+gcov_tt.*gcov_zz))) ...
.^(-1/2).*((I1+dlambda_dt).^(-2).*((-1).*dgcov_zz_dz.*gcov_rt.^2+ ...
2.*dgcov_tz_dz.*gcov_rt.*gcov_rz+(-1).*dgcov_tt_dz.*gcov_rz.^2+( ...
-2).*dgcov_rz_dz.*gcov_rz.*gcov_tt+2.*dgcov_rz_dz.*gcov_rt.* ...
gcov_tz+2.*dgcov_rt_dz.*gcov_rz.*gcov_tz+(-2).*dgcov_rt_dz.* ...
gcov_rt.*gcov_zz+gcov_rr.*(dgcov_zz_dz.*gcov_tt+(-2).* ...
dgcov_tz_dz.*gcov_tz+dgcov_tt_dz.*gcov_zz)+dgcov_rr_dz.*((-1).* ...
gcov_tz.^2+gcov_tt.*gcov_zz))+(-2).*(I1+dlambda_dt).^(-3).* ...
dlambda_dtdz.*((-1).*gcov_rz.^2.*gcov_tt+2.*gcov_rt.*gcov_rz.* ...
gcov_tz+(-1).*gcov_rt.^2.*gcov_zz+gcov_rr.*((-1).*gcov_tz.^2+ ...
gcov_tt.*gcov_zz)));


figure;
subplot(1,3,1);
mesh(JPEST);
title('JPEST (DESC)');
subplot(1,3,2);
mesh(Jpest);
title('JPEST (Transform)');
subplot(1,3,3);
mesh((Jpest-JPEST)./JPEST);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(dJPEST_drho);
title('dJPEST/drho (DESC)');
subplot(1,3,2);
mesh(dJpest_drho);
title('dJPEST/drho (Transform)');
subplot(1,3,3);
mesh((dJpest_drho-dJPEST_drho)./dJPEST_drho);
title('Relative Error');


figure;
subplot(1,3,1);
mesh(dJPEST_dtheta);
title('dJPEST/dtheta (DESC)');
subplot(1,3,2);
mesh(dJpest_dtheta);
title('dJPEST/dtheta (Transform)');
subplot(1,3,3);
mesh((dJpest_dtheta-dJPEST_dtheta)./dJPEST_dtheta);
title('Relative Error');


%% Jpara/B

[jp,djp_dr,djp_dt] = interp_2d_d1_(refined_Jpara);
djp_dz = zeros(N_rho,N_theta);

djp_drho=djp_dr+(-1).*dlambda_dr.*(I1+dlambda_dt).^(-1).*djp_dt;
djp_dtheta=(I1+dlambda_dt).^(-1).*djp_dt;
djp_dphi=(-1).*(I1+dlambda_dt).^(-1).*dlambda_dz.*djp_dt+djp_dz;

jp_B = jp./B;
djp_B_drho = (djp_drho.*B-dB_drho.*jp)./B.^2;
djp_B_dtheta = (djp_dtheta.*B-dB_dtheta.*jp)./B.^2;
djp_B_dphi = (djp_dphi.*B-dB_dphi.*jp)./B.^2;

figure;
subplot(1,3,1);
mesh(jp_B);
title('Jpara/B');
subplot(1,3,2);
mesh(djp_B_drho);
title('d(Jpara/B)/drho');
subplot(1,3,3);
mesh(djp_B_dtheta);
title('d(Jpara/B)/dtheta');

%% Shifted Metric Coordinate (SFT)

dq_drho = dq_dr;
dq_drho2 = dq_dr2;

gcon_rhorho = PESTcon_xx;
gcon_rhotheta = PESTcon_xy;
gcon_rhophi = PESTcon_xz;
gcon_thetatheta = PESTcon_yy;
gcon_thetaphi = PESTcon_yz;
gcon_phiphi = PESTcon_zz;

gcov_rhorho = PESTcov_xx;
gcov_rhotheta = PESTcov_xy;
gcov_rhophi = PESTcov_xz;
gcov_thetatheta = PESTcov_yy;
gcov_thetaphi = PESTcov_yz;
gcov_phiphi = PESTcov_zz;

vars = ["rho","theta","phi"];
for i=1:3
    for j=i:3
        for k=1:3
            varname = ['dgcon_',char(vars(i)),char(vars(j)),'_d',char(vars(k))];        
            eval([varname,' = dgconPEST_d',char(vars(k)),'{',num2str(i),',',num2str(j),'};']);
            varname = ['dgcov_',char(vars(i)),char(vars(j)),'_d',char(vars(k))];        
            eval([varname,' = dgcovPEST_d',char(vars(k)),'{',num2str(i),',',num2str(j),'};']);
        end
    end
end

gconSFT=reshape({Drho.^(-2).*gcon_rhorho;
Drho.^(-1).*gcon_rhotheta;
Drho.^(-1).*(gcon_rhophi+(-1).*gcon_rhotheta.*q);
Drho.^(-1).*gcon_rhotheta;
gcon_thetatheta;
gcon_thetaphi+(-1).*gcon_thetatheta.*q;
Drho.^(-1).*(gcon_rhophi+(-1).*gcon_rhotheta.*q);
gcon_thetaphi+(-1).*gcon_thetatheta.*q;
gcon_phiphi+(-2).*gcon_thetaphi.*q+gcon_thetatheta.*q.^2;
},3,3);


dgconSFT_dx=reshape({dgcon_rhorho_drho.*Drho.^(-1);
dgcon_rhotheta_drho;
dgcon_rhophi_drho+(-1).*dq_drho.*gcon_rhotheta+(-1).* ...
dgcon_rhotheta_drho.*q;
dgcon_rhotheta_drho;
dgcon_thetatheta_drho.*Drho;
(-1).*Drho.*((-1).*dgcon_thetaphi_drho+dq_drho.*gcon_thetatheta+ ...
dgcon_thetatheta_drho.*q);
dgcon_rhophi_drho+(-1).*dq_drho.*gcon_rhotheta+(-1).* ...
dgcon_rhotheta_drho.*q;
(-1).*Drho.*((-1).*dgcon_thetaphi_drho+dq_drho.*gcon_thetatheta+ ...
dgcon_thetatheta_drho.*q);
Drho.*(dgcon_phiphi_drho+(-2).*dq_drho.*gcon_thetaphi+2.*((-1).* ...
dgcon_thetaphi_drho+dq_drho.*gcon_thetatheta).*q+ ...
dgcon_thetatheta_drho.*q.^2);
},3,3);


dgconSFT_dy=reshape({Drho.^(-2).*(dgcon_rhorho_dtheta+dgcon_rhorho_dphi.*q);
Drho.^(-1).*(dgcon_rhotheta_dtheta+dgcon_rhotheta_dphi.*q);
Drho.^(-1).*(dgcon_rhophi_dtheta+(-1).*dq_drho.*gcon_rhorho+( ...
dgcon_rhophi_dphi+(-1).*dgcon_rhotheta_dtheta).*q+(-1).* ...
dgcon_rhotheta_dphi.*q.^2);
Drho.^(-1).*(dgcon_rhotheta_dtheta+dgcon_rhotheta_dphi.*q);
dgcon_thetatheta_dtheta+dgcon_thetatheta_dphi.*q;
dgcon_thetaphi_dtheta+(-1).*dq_drho.*gcon_rhotheta+( ...
dgcon_thetaphi_dphi+(-1).*dgcon_thetatheta_dtheta).*q+(-1).* ...
dgcon_thetatheta_dphi.*q.^2;
Drho.^(-1).*(dgcon_rhophi_dtheta+(-1).*dq_drho.*gcon_rhorho+( ...
dgcon_rhophi_dphi+(-1).*dgcon_rhotheta_dtheta).*q+(-1).* ...
dgcon_rhotheta_dphi.*q.^2);
dgcon_thetaphi_dtheta+(-1).*dq_drho.*gcon_rhotheta+( ...
dgcon_thetaphi_dphi+(-1).*dgcon_thetatheta_dtheta).*q+(-1).* ...
dgcon_thetatheta_dphi.*q.^2;
dgcon_phiphi_dtheta+(-2).*dq_drho.*gcon_rhophi+(dgcon_phiphi_dphi+ ...
(-2).*dgcon_thetaphi_dtheta+2.*dq_drho.*gcon_rhotheta).*q+((-2).* ...
dgcon_thetaphi_dphi+dgcon_thetatheta_dtheta).*q.^2+ ...
dgcon_thetatheta_dphi.*q.^3;
},3,3);


dgconSFT_dz=reshape({dgcon_rhorho_dphi.*Drho.^(-2);
dgcon_rhotheta_dphi.*Drho.^(-1);
Drho.^(-1).*(dgcon_rhophi_dphi+(-1).*dgcon_rhotheta_dphi.*q);
dgcon_rhotheta_dphi.*Drho.^(-1);
dgcon_thetatheta_dphi;
dgcon_thetaphi_dphi+(-1).*dgcon_thetatheta_dphi.*q;
Drho.^(-1).*(dgcon_rhophi_dphi+(-1).*dgcon_rhotheta_dphi.*q);
dgcon_thetaphi_dphi+(-1).*dgcon_thetatheta_dphi.*q;
dgcon_phiphi_dphi+(-2).*dgcon_thetaphi_dphi.*q+ ...
dgcon_thetatheta_dphi.*q.^2;
},3,3);


gcovSFT=reshape({Drho.^2.*gcov_rhorho;
Drho.*(gcov_rhotheta+gcov_rhophi.*q);
Drho.*gcov_rhophi;
Drho.*(gcov_rhotheta+gcov_rhophi.*q);
gcov_thetatheta+q.*(2.*gcov_thetaphi+gcov_phiphi.*q);
gcov_thetaphi+gcov_phiphi.*q;
Drho.*gcov_rhophi;
gcov_thetaphi+gcov_phiphi.*q;
gcov_phiphi;
},3,3);


dgcovSFT_dx=reshape({dgcov_rhorho_drho.*Drho.^3;
Drho.^2.*(dgcov_rhotheta_drho+dq_drho.*gcov_rhophi+ ...
dgcov_rhophi_drho.*q);
dgcov_rhophi_drho.*Drho.^2;
Drho.^2.*(dgcov_rhotheta_drho+dq_drho.*gcov_rhophi+ ...
dgcov_rhophi_drho.*q);
Drho.*(dgcov_thetatheta_drho+2.*dq_drho.*gcov_thetaphi+2.*( ...
dgcov_thetaphi_drho+dq_drho.*gcov_phiphi).*q+dgcov_phiphi_drho.* ...
q.^2);
Drho.*(dgcov_thetaphi_drho+dq_drho.*gcov_phiphi+ ...
dgcov_phiphi_drho.*q);
dgcov_rhophi_drho.*Drho.^2;
Drho.*(dgcov_thetaphi_drho+dq_drho.*gcov_phiphi+ ...
dgcov_phiphi_drho.*q);
dgcov_phiphi_drho.*Drho;
},3,3);


dgcovSFT_dy=reshape({Drho.^2.*(dgcov_rhorho_dtheta+2.*dq_drho.*gcov_rhophi+ ...
dgcov_rhorho_dphi.*q);
Drho.*(dgcov_rhotheta_dtheta+dq_drho.*gcov_thetaphi+( ...
dgcov_rhophi_dtheta+dgcov_rhotheta_dphi+dq_drho.*gcov_phiphi).*q+ ...
dgcov_rhophi_dphi.*q.^2);
Drho.*(dgcov_rhophi_dtheta+dq_drho.*gcov_phiphi+ ...
dgcov_rhophi_dphi.*q);
Drho.*(dgcov_rhotheta_dtheta+dq_drho.*gcov_thetaphi+( ...
dgcov_rhophi_dtheta+dgcov_rhotheta_dphi+dq_drho.*gcov_phiphi).*q+ ...
dgcov_rhophi_dphi.*q.^2);
dgcov_thetatheta_dtheta+(2.*dgcov_thetaphi_dtheta+ ...
dgcov_thetatheta_dphi).*q+(dgcov_phiphi_dtheta+2.* ...
dgcov_thetaphi_dphi).*q.^2+dgcov_phiphi_dphi.*q.^3;
dgcov_thetaphi_dtheta+(dgcov_phiphi_dtheta+dgcov_thetaphi_dphi).* ...
q+dgcov_phiphi_dphi.*q.^2;
Drho.*(dgcov_rhophi_dtheta+dq_drho.*gcov_phiphi+ ...
dgcov_rhophi_dphi.*q);
dgcov_thetaphi_dtheta+(dgcov_phiphi_dtheta+dgcov_thetaphi_dphi).* ...
q+dgcov_phiphi_dphi.*q.^2;
dgcov_phiphi_dtheta+dgcov_phiphi_dphi.*q;
},3,3);


dgcovSFT_dz=reshape({dgcov_rhorho_dphi.*Drho.^2;
Drho.*(dgcov_rhotheta_dphi+dgcov_rhophi_dphi.*q);
dgcov_rhophi_dphi.*Drho;
Drho.*(dgcov_rhotheta_dphi+dgcov_rhophi_dphi.*q);
dgcov_thetatheta_dphi+q.*(2.*dgcov_thetaphi_dphi+ ...
dgcov_phiphi_dphi.*q);
dgcov_thetaphi_dphi+dgcov_phiphi_dphi.*q;
dgcov_rhophi_dphi.*Drho;
dgcov_thetaphi_dphi+dgcov_phiphi_dphi.*q;
dgcov_phiphi_dphi;
},3,3);

%% Field Aligned Coordinate (SFA)

ghost = 2;

q_withghost = zeros(N_rho,N_theta+2*ghost);
dq_drho_withghost = zeros(N_rho,N_theta+2*ghost);
dq_drho2_withghost = zeros(N_rho,N_theta+2*ghost);
thetap_withghost = zeros(N_rho,N_theta+2*ghost);

for j=1:N_theta+2*ghost
    q_withghost(:,j) = q(:,1);
    dq_drho_withghost(:,j) = dq_drho(:,1);
    dq_drho2_withghost(:,j)= dq_drho2(:,1);
end

for i=1:N_rho
    thetap_withghost(i,:) = -pi+(-(ghost-0.5):1:N_theta+(ghost-0.5))/N_theta*2*pi;
end

if ifStaggered == 1
    thetap_withghost = thetap_withghost-0.5*2*pi/N_theta;
end

qtheta = q_withghost.*thetap_withghost;

vars = ["rho","theta","phi"];

for i=1:3
    for j=i:3
        varname = ['gcov_',char(vars(i)),char(vars(j))];
        eval([varname,' = ','[',varname,'(:,end-ghost+1:end),',varname,',',varname,'(:,1:ghost)];']);
        varname = ['gcon_',char(vars(i)),char(vars(j))];
        eval([varname,' = ','[',varname,'(:,end-ghost+1:end),',varname,',',varname,'(:,1:ghost)];']);
    end
end

for i=1:3
    for j=i:3
        for k=1:3
            varname = ['dgcov_',char(vars(i)),char(vars(j)),'_d',char(vars(k))];        
            eval([varname,' = ','[',varname,'(:,end-ghost+1:end),',varname,',',varname,'(:,1:ghost)];']);
            varname = ['dgcon_',char(vars(i)),char(vars(j)),'_d',char(vars(k))];        
            eval([varname,' = ','[',varname,'(:,end-ghost+1:end),',varname,',',varname,'(:,1:ghost)];']);
        end
    end
end


gconSFA=reshape({Drho.^(-2).*gcon_rhorho;
Drho.^(-1).*gcon_rhotheta;
Drho.^(-1).*(gcon_rhophi+(-1).*gcon_rhotheta.*q_withghost+(-1).*dq_drho_withghost.* ...
  gcon_rhorho.*thetap_withghost);
Drho.^(-1).*gcon_rhotheta;
gcon_thetatheta;
gcon_thetaphi+(-1).*gcon_thetatheta.*q_withghost+(-1).*dq_drho_withghost.* ...
  gcon_rhotheta.*thetap_withghost;
Drho.^(-1).*(gcon_rhophi+(-1).*gcon_rhotheta.*q_withghost+(-1).*dq_drho_withghost.* ...
  gcon_rhorho.*thetap_withghost);
gcon_thetaphi+(-1).*gcon_thetatheta.*q_withghost+(-1).*dq_drho_withghost.* ...
  gcon_rhotheta.*thetap_withghost;
gcon_phiphi+gcon_thetatheta.*q_withghost.^2+dq_drho_withghost.*thetap_withghost.*((-2).*gcon_rhophi+ ...
  dq_drho_withghost.*gcon_rhorho.*thetap_withghost)+(-2).*q_withghost.*(gcon_thetaphi+(-1).*dq_drho_withghost.* ...
  gcon_rhotheta.*thetap_withghost);
},3,3);


dgconSFA_dx=reshape({Drho.^(-1).*(dgcon_rhorho_drho+dgcon_rhorho_dphi.*dq_drho_withghost.*thetap_withghost);
dgcon_rhotheta_drho+dgcon_rhotheta_dphi.*dq_drho_withghost.*thetap_withghost;
dgcon_rhophi_drho+(-1).*dq_drho_withghost.*gcon_rhotheta+(-1).* ...
  dgcon_rhotheta_drho.*q_withghost+dgcon_rhophi_dphi.*dq_drho_withghost.*thetap_withghost+(-1).* ...
  dgcon_rhorho_drho.*dq_drho_withghost.*thetap_withghost+(-1).*dq_drho2_withghost.*gcon_rhorho.*thetap_withghost+(-1) ...
  .*dgcon_rhotheta_dphi.*dq_drho_withghost.*q_withghost.*thetap_withghost+(-1).*dgcon_rhorho_dphi.* ...
  dq_drho_withghost.^2.*thetap_withghost.^2;
dgcon_rhotheta_drho+dgcon_rhotheta_dphi.*dq_drho_withghost.*thetap_withghost;
Drho.*(dgcon_thetatheta_drho+dgcon_thetatheta_dphi.*dq_drho_withghost.*thetap_withghost);
Drho.*(dgcon_thetaphi_drho+(-1).*dq_drho_withghost.*gcon_thetatheta+(-1).* ...
  dgcon_thetatheta_drho.*q_withghost+(-1).*dgcon_rhotheta_drho.*dq_drho_withghost.*thetap_withghost+( ...
  -1).*dq_drho2_withghost.*gcon_rhotheta.*thetap_withghost+dq_drho_withghost.*thetap_withghost.*(dgcon_thetaphi_dphi+( ...
  -1).*dgcon_thetatheta_dphi.*q_withghost+(-1).*dgcon_rhotheta_dphi.*dq_drho_withghost.* ...
  thetap_withghost));
dgcon_rhophi_drho+(-1).*dq_drho_withghost.*gcon_rhotheta+(-1).* ...
  dgcon_rhotheta_drho.*q_withghost+dgcon_rhophi_dphi.*dq_drho_withghost.*thetap_withghost+(-1).* ...
  dgcon_rhorho_drho.*dq_drho_withghost.*thetap_withghost+(-1).*dq_drho2_withghost.*gcon_rhorho.*thetap_withghost+(-1) ...
  .*dgcon_rhotheta_dphi.*dq_drho_withghost.*q_withghost.*thetap_withghost+(-1).*dgcon_rhorho_dphi.* ...
  dq_drho_withghost.^2.*thetap_withghost.^2;
Drho.*(dgcon_thetaphi_drho+(-1).*dq_drho_withghost.*gcon_thetatheta+(-1).* ...
  dgcon_thetatheta_drho.*q_withghost+(-1).*dgcon_rhotheta_drho.*dq_drho_withghost.*thetap_withghost+( ...
  -1).*dq_drho2_withghost.*gcon_rhotheta.*thetap_withghost+dq_drho_withghost.*thetap_withghost.*(dgcon_thetaphi_dphi+( ...
  -1).*dgcon_thetatheta_dphi.*q_withghost+(-1).*dgcon_rhotheta_dphi.*dq_drho_withghost.* ...
  thetap_withghost));
Drho.*(dgcon_phiphi_drho+2.*dq_drho_withghost.*gcon_thetatheta.*q_withghost+ ...
  dgcon_thetatheta_drho.*q_withghost.^2+dq_drho2_withghost.*thetap_withghost.*((-2).*gcon_rhophi+ ...
  dq_drho_withghost.*gcon_rhorho.*thetap_withghost)+dq_drho_withghost.*thetap_withghost.*((-2).*dgcon_rhophi_drho+ ...
  dgcon_rhorho_drho.*dq_drho_withghost.*thetap_withghost+dq_drho2_withghost.*gcon_rhorho.*thetap_withghost)+2.* ...
  dq_drho_withghost.*((-1).*gcon_thetaphi+dq_drho_withghost.*gcon_rhotheta.*thetap_withghost)+2.*q_withghost.*(( ...
  -1).*dgcon_thetaphi_drho+dgcon_rhotheta_drho.*dq_drho_withghost.*thetap_withghost+ ...
  dq_drho2_withghost.*gcon_rhotheta.*thetap_withghost)+dq_drho_withghost.*thetap_withghost.*(dgcon_phiphi_dphi+(-2).* ...
  dgcon_thetaphi_dphi.*q_withghost+dgcon_thetatheta_dphi.*q_withghost.^2+2.*dq_drho_withghost.*(( ...
  -1).*dgcon_rhophi_dphi+dgcon_rhotheta_dphi.*q_withghost).*thetap_withghost+ ...
  dgcon_rhorho_dphi.*dq_drho_withghost.^2.*thetap_withghost.^2));
},3,3);


dgconSFA_dy=reshape({Drho.^(-2).*(dgcon_rhorho_dtheta+dgcon_rhorho_dphi.*q_withghost);
Drho.^(-1).*(dgcon_rhotheta_dtheta+dgcon_rhotheta_dphi.*q_withghost);
(-1).*Drho.^(-1).*((-1).*dgcon_rhophi_dtheta+dq_drho_withghost.*gcon_rhorho+ ...
  dgcon_rhotheta_dphi.*q_withghost.^2+dgcon_rhorho_dtheta.*dq_drho_withghost.*thetap_withghost+q_withghost.*((-1) ...
  .*dgcon_rhophi_dphi+dgcon_rhotheta_dtheta+dgcon_rhorho_dphi.* ...
  dq_drho_withghost.*thetap_withghost));
Drho.^(-1).*(dgcon_rhotheta_dtheta+dgcon_rhotheta_dphi.*q_withghost);
dgcon_thetatheta_dtheta+dgcon_thetatheta_dphi.*q_withghost;
dgcon_thetaphi_dtheta+(-1).*dq_drho_withghost.*gcon_rhotheta+(-1).* ...
  dgcon_thetatheta_dphi.*q_withghost.^2+(-1).*dgcon_rhotheta_dtheta.*dq_drho_withghost.* ...
  thetap_withghost+(-1).*q_withghost.*((-1).*dgcon_thetaphi_dphi+dgcon_thetatheta_dtheta+ ...
  dgcon_rhotheta_dphi.*dq_drho_withghost.*thetap_withghost);
(-1).*Drho.^(-1).*((-1).*dgcon_rhophi_dtheta+dq_drho_withghost.*gcon_rhorho+ ...
  dgcon_rhotheta_dphi.*q_withghost.^2+dgcon_rhorho_dtheta.*dq_drho_withghost.*thetap_withghost+q_withghost.*((-1) ...
  .*dgcon_rhophi_dphi+dgcon_rhotheta_dtheta+dgcon_rhorho_dphi.* ...
  dq_drho_withghost.*thetap_withghost));
dgcon_thetaphi_dtheta+(-1).*dq_drho_withghost.*gcon_rhotheta+(-1).* ...
  dgcon_thetatheta_dphi.*q_withghost.^2+(-1).*dgcon_rhotheta_dtheta.*dq_drho_withghost.* ...
  thetap_withghost+(-1).*q_withghost.*((-1).*dgcon_thetaphi_dphi+dgcon_thetatheta_dtheta+ ...
  dgcon_rhotheta_dphi.*dq_drho_withghost.*thetap_withghost);
dgcon_phiphi_dtheta+(-2).*dq_drho_withghost.*gcon_rhophi+ ...
  dgcon_thetatheta_dphi.*q_withghost.^3+(-2).*dgcon_rhophi_dtheta.*dq_drho_withghost.*thetap_withghost+ ...
  2.*dq_drho_withghost.^2.*gcon_rhorho.*thetap_withghost+dgcon_rhorho_dtheta.*dq_drho_withghost.^2.* ...
  thetap_withghost.^2+q_withghost.^2.*((-2).*dgcon_thetaphi_dphi+dgcon_thetatheta_dtheta+2.* ...
  dgcon_rhotheta_dphi.*dq_drho_withghost.*thetap_withghost)+q_withghost.*(dgcon_phiphi_dphi+(-2).* ...
  dgcon_thetaphi_dtheta+2.*dq_drho_withghost.*gcon_rhotheta+2.*((-1).* ...
  dgcon_rhophi_dphi+dgcon_rhotheta_dtheta).*dq_drho_withghost.*thetap_withghost+ ...
  dgcon_rhorho_dphi.*dq_drho_withghost.^2.*thetap_withghost.^2);
},3,3);


dgconSFA_dz=reshape({dgcon_rhorho_dphi.*Drho.^(-2);
dgcon_rhotheta_dphi.*Drho.^(-1);
Drho.^(-1).*(dgcon_rhophi_dphi+(-1).*dgcon_rhotheta_dphi.*q_withghost+(-1).* ...
  dgcon_rhorho_dphi.*dq_drho_withghost.*thetap_withghost);
dgcon_rhotheta_dphi.*Drho.^(-1);
dgcon_thetatheta_dphi;
dgcon_thetaphi_dphi+(-1).*dgcon_thetatheta_dphi.*q_withghost+(-1).* ...
  dgcon_rhotheta_dphi.*dq_drho_withghost.*thetap_withghost;
Drho.^(-1).*(dgcon_rhophi_dphi+(-1).*dgcon_rhotheta_dphi.*q_withghost+(-1).* ...
  dgcon_rhorho_dphi.*dq_drho_withghost.*thetap_withghost);
dgcon_thetaphi_dphi+(-1).*dgcon_thetatheta_dphi.*q_withghost+(-1).* ...
  dgcon_rhotheta_dphi.*dq_drho_withghost.*thetap_withghost;
dgcon_phiphi_dphi+(-2).*dgcon_thetaphi_dphi.*q_withghost+ ...
  dgcon_thetatheta_dphi.*q_withghost.^2+2.*dq_drho_withghost.*((-1).*dgcon_rhophi_dphi+ ...
  dgcon_rhotheta_dphi.*q_withghost).*thetap_withghost+dgcon_rhorho_dphi.*dq_drho_withghost.^2.*thetap_withghost.^2;
},3,3);


gcovSFA=reshape({Drho.^2.*(gcov_rhorho+dq_drho_withghost.*thetap_withghost.*(2.*gcov_rhophi+dq_drho_withghost.* ...
  gcov_phiphi.*thetap_withghost));
Drho.*(gcov_rhotheta+dq_drho_withghost.*gcov_thetaphi.*thetap_withghost+q_withghost.*(gcov_rhophi+ ...
  dq_drho_withghost.*gcov_phiphi.*thetap_withghost));
Drho.*(gcov_rhophi+dq_drho_withghost.*gcov_phiphi.*thetap_withghost);
Drho.*(gcov_rhotheta+gcov_rhophi.*q_withghost+dq_drho_withghost.*(gcov_thetaphi+ ...
  gcov_phiphi.*q_withghost).*thetap_withghost);
gcov_thetatheta+q_withghost.*(2.*gcov_thetaphi+gcov_phiphi.*q_withghost);
gcov_thetaphi+gcov_phiphi.*q_withghost;
Drho.*(gcov_rhophi+dq_drho_withghost.*gcov_phiphi.*thetap_withghost);
gcov_thetaphi+gcov_phiphi.*q_withghost;
gcov_phiphi;
},3,3);


dgcovSFA_dx=reshape({Drho.^3.*(dgcov_rhorho_drho+2.*dgcov_rhophi_drho.*dq_drho_withghost.*thetap_withghost+ ...
  dgcov_rhorho_dphi.*dq_drho_withghost.*thetap_withghost+2.*dq_drho2_withghost.*gcov_rhophi.*thetap_withghost+ ...
  dgcov_phiphi_drho.*dq_drho_withghost.^2.*thetap_withghost.^2+2.*dgcov_rhophi_dphi.* ...
  dq_drho_withghost.^2.*thetap_withghost.^2+2.*dq_drho_withghost.*dq_drho2_withghost.*gcov_phiphi.*thetap_withghost.^2+ ...
  dgcov_phiphi_dphi.*dq_drho_withghost.^3.*thetap_withghost.^3);
Drho.^2.*(dgcov_rhotheta_drho+dgcov_thetaphi_drho.*dq_drho_withghost.*thetap_withghost+ ...
  dq_drho2_withghost.*gcov_thetaphi.*thetap_withghost+dq_drho_withghost.*(gcov_rhophi+dq_drho_withghost.* ...
  gcov_phiphi.*thetap_withghost)+q_withghost.*(dgcov_rhophi_drho+dgcov_phiphi_drho.*dq_drho_withghost.* ...
  thetap_withghost+dq_drho2_withghost.*gcov_phiphi.*thetap_withghost)+dq_drho_withghost.*thetap_withghost.*(dgcov_rhotheta_dphi+ ...
  dgcov_thetaphi_dphi.*dq_drho_withghost.*thetap_withghost+q_withghost.*(dgcov_rhophi_dphi+ ...
  dgcov_phiphi_dphi.*dq_drho_withghost.*thetap_withghost)));
Drho.^2.*(dgcov_rhophi_drho+(dgcov_phiphi_drho+dgcov_rhophi_dphi) ...
  .*dq_drho_withghost.*thetap_withghost+dq_drho2_withghost.*gcov_phiphi.*thetap_withghost+dgcov_phiphi_dphi.* ...
  dq_drho_withghost.^2.*thetap_withghost.^2);
Drho.^2.*(dgcov_rhotheta_drho+dq_drho_withghost.*gcov_rhophi+ ...
  dgcov_rhophi_drho.*q_withghost+dq_drho_withghost.*(dgcov_thetaphi_drho+dq_drho_withghost.* ...
  gcov_phiphi+dgcov_phiphi_drho.*q_withghost).*thetap_withghost+dq_drho2_withghost.*(gcov_thetaphi+ ...
  gcov_phiphi.*q_withghost).*thetap_withghost+dq_drho_withghost.*thetap_withghost.*(dgcov_rhotheta_dphi+ ...
  dgcov_rhophi_dphi.*q_withghost+dq_drho_withghost.*(dgcov_thetaphi_dphi+ ...
  dgcov_phiphi_dphi.*q_withghost).*thetap_withghost));
Drho.*(dgcov_thetatheta_drho+2.*dq_drho_withghost.*gcov_thetaphi+ ...
  dgcov_thetatheta_dphi.*dq_drho_withghost.*thetap_withghost+q_withghost.^2.*(dgcov_phiphi_drho+ ...
  dgcov_phiphi_dphi.*dq_drho_withghost.*thetap_withghost)+2.*q_withghost.*(dgcov_thetaphi_drho+ ...
  dq_drho_withghost.*gcov_phiphi+dgcov_thetaphi_dphi.*dq_drho_withghost.*thetap_withghost));
Drho.*(dgcov_thetaphi_drho+dq_drho_withghost.*gcov_phiphi+ ...
  dgcov_phiphi_drho.*q_withghost+dq_drho_withghost.*(dgcov_thetaphi_dphi+ ...
  dgcov_phiphi_dphi.*q_withghost).*thetap_withghost);
Drho.^2.*(dgcov_rhophi_drho+(dgcov_phiphi_drho+dgcov_rhophi_dphi) ...
  .*dq_drho_withghost.*thetap_withghost+dq_drho2_withghost.*gcov_phiphi.*thetap_withghost+dgcov_phiphi_dphi.* ...
  dq_drho_withghost.^2.*thetap_withghost.^2);
Drho.*(dgcov_thetaphi_drho+dq_drho_withghost.*gcov_phiphi+ ...
  dgcov_phiphi_drho.*q_withghost+dq_drho_withghost.*(dgcov_thetaphi_dphi+ ...
  dgcov_phiphi_dphi.*q_withghost).*thetap_withghost);
Drho.*(dgcov_phiphi_drho+dgcov_phiphi_dphi.*dq_drho_withghost.*thetap_withghost);
},3,3);


dgcovSFA_dy=reshape({Drho.^2.*(dgcov_rhorho_dtheta+2.*dq_drho_withghost.*gcov_rhophi+ ...
  dgcov_rhorho_dphi.*q_withghost+2.*dgcov_rhophi_dtheta.*dq_drho_withghost.*thetap_withghost+2.* ...
  dq_drho_withghost.^2.*gcov_phiphi.*thetap_withghost+2.*dgcov_rhophi_dphi.*dq_drho_withghost.*q_withghost.*thetap_withghost+ ...
  dgcov_phiphi_dtheta.*dq_drho_withghost.^2.*thetap_withghost.^2+dgcov_phiphi_dphi.* ...
  dq_drho_withghost.^2.*q_withghost.*thetap_withghost.^2);
Drho.*(dgcov_rhotheta_dtheta+dq_drho_withghost.*gcov_thetaphi+ ...
  dgcov_thetaphi_dtheta.*dq_drho_withghost.*thetap_withghost+q_withghost.^2.*(dgcov_rhophi_dphi+ ...
  dgcov_phiphi_dphi.*dq_drho_withghost.*thetap_withghost)+q_withghost.*(dgcov_rhophi_dtheta+ ...
  dgcov_rhotheta_dphi+dq_drho_withghost.*gcov_phiphi+dgcov_phiphi_dtheta.* ...
  dq_drho_withghost.*thetap_withghost+dgcov_thetaphi_dphi.*dq_drho_withghost.*thetap_withghost));
Drho.*(dgcov_rhophi_dtheta+dq_drho_withghost.*gcov_phiphi+ ...
  dgcov_phiphi_dtheta.*dq_drho_withghost.*thetap_withghost+q_withghost.*(dgcov_rhophi_dphi+ ...
  dgcov_phiphi_dphi.*dq_drho_withghost.*thetap_withghost));
Drho.*(dgcov_rhotheta_dtheta+dgcov_rhophi_dtheta.*q_withghost+dq_drho_withghost.*( ...
  gcov_thetaphi+gcov_phiphi.*q_withghost)+dq_drho_withghost.*(dgcov_thetaphi_dtheta+ ...
  dgcov_phiphi_dtheta.*q_withghost).*thetap_withghost+q_withghost.*(dgcov_rhotheta_dphi+ ...
  dgcov_rhophi_dphi.*q_withghost+dq_drho_withghost.*(dgcov_thetaphi_dphi+ ...
  dgcov_phiphi_dphi.*q_withghost).*thetap_withghost));
dgcov_thetatheta_dtheta+(2.*dgcov_thetaphi_dtheta+ ...
  dgcov_thetatheta_dphi).*q_withghost+(dgcov_phiphi_dtheta+2.* ...
  dgcov_thetaphi_dphi).*q_withghost.^2+dgcov_phiphi_dphi.*q_withghost.^3;
dgcov_thetaphi_dtheta+(dgcov_phiphi_dtheta+dgcov_thetaphi_dphi).* ...
  q_withghost+dgcov_phiphi_dphi.*q_withghost.^2;
Drho.*(dgcov_rhophi_dtheta+dq_drho_withghost.*gcov_phiphi+ ...
  dgcov_phiphi_dtheta.*dq_drho_withghost.*thetap_withghost+q_withghost.*(dgcov_rhophi_dphi+ ...
  dgcov_phiphi_dphi.*dq_drho_withghost.*thetap_withghost));
dgcov_thetaphi_dtheta+(dgcov_phiphi_dtheta+dgcov_thetaphi_dphi).* ...
  q_withghost+dgcov_phiphi_dphi.*q_withghost.^2;
dgcov_phiphi_dtheta+dgcov_phiphi_dphi.*q_withghost;
},3,3);


dgcovSFA_dz=reshape({Drho.^2.*(dgcov_rhorho_dphi+dq_drho_withghost.*thetap_withghost.*(2.*dgcov_rhophi_dphi+ ...
  dgcov_phiphi_dphi.*dq_drho_withghost.*thetap_withghost));
Drho.*(dgcov_rhotheta_dphi+dgcov_thetaphi_dphi.*dq_drho_withghost.*thetap_withghost+q_withghost.*( ...
  dgcov_rhophi_dphi+dgcov_phiphi_dphi.*dq_drho_withghost.*thetap_withghost));
Drho.*(dgcov_rhophi_dphi+dgcov_phiphi_dphi.*dq_drho_withghost.*thetap_withghost);
Drho.*(dgcov_rhotheta_dphi+dgcov_rhophi_dphi.*q_withghost+dq_drho_withghost.*( ...
  dgcov_thetaphi_dphi+dgcov_phiphi_dphi.*q_withghost).*thetap_withghost);
dgcov_thetatheta_dphi+q_withghost.*(2.*dgcov_thetaphi_dphi+ ...
  dgcov_phiphi_dphi.*q_withghost);
dgcov_thetaphi_dphi+dgcov_phiphi_dphi.*q_withghost;
Drho.*(dgcov_rhophi_dphi+dgcov_phiphi_dphi.*dq_drho_withghost.*thetap_withghost);
dgcov_thetaphi_dphi+dgcov_phiphi_dphi.*q_withghost;
dgcov_phiphi_dphi;
},3,3);

%%

nnz(dR_dphi+dZ_dphi+ ...
    dB_dphi+dB_drhodphi+dB_dthetadphi+dB_dphi2+ ...
    dJpest_dphi+ ...
    djp_B_dphi+ ...
    dgconPEST_dphi{1,1}+dgconPEST_dphi{1,2}+dgconPEST_dphi{1,3}+dgconPEST_dphi{2,2}+dgconPEST_dphi{2,3}+dgconPEST_dphi{3,3}+ ...
    dgcovPEST_dphi{1,1}+dgcovPEST_dphi{1,2}+dgcovPEST_dphi{1,3}+dgcovPEST_dphi{2,2}+dgcovPEST_dphi{2,3}+dgcovPEST_dphi{3,3}+ ...
    dgconSFT_dz{1,1}+dgconSFT_dz{1,2}+dgconSFT_dz{1,3}+dgconSFT_dz{2,2}+dgconSFT_dz{2,3}+dgconSFT_dz{3,3}+ ...
    dgcovSFT_dz{1,1}+dgcovSFT_dz{1,2}+dgcovSFT_dz{1,3}+dgcovSFT_dz{2,2}+dgcovSFT_dz{2,3}+dgcovSFT_dz{3,3}+ ...
    nnz(dgconSFA_dz{1,1}+dgconSFA_dz{1,2}+dgconSFA_dz{1,3}+dgconSFA_dz{2,2}+dgconSFA_dz{2,3}+dgconSFA_dz{3,3}+ ...
    dgcovSFA_dz{1,1}+dgcovSFA_dz{1,2}+dgcovSFA_dz{1,3}+dgcovSFA_dz{2,2}+dgcovSFA_dz{2,3}+dgcovSFA_dz{3,3}))


%%

